Ads:
  description: "Lietotne satur rekl\u0101mu"
  name: "Rekl\u0101mas"
DisabledAlgorithm:
  description: "\u0160ai lietotnei ir v\u0101j\u0161 dro\u0161\u012Bbas paraksts"
  name: "Parakst\u012Bta ar nedro\u0161u algoritmu"
KnownVuln:
  description: "\u0160\u012B lietotne satur zin\u0101mu dro\u0161\u012Bbas ievainojam\u012B\
    bu"
  name: "Zin\u0101ma ievainojam\u012Bba"
NoSourceSince:
  description: "Pirmkods vairs nav pieejams, atjaunin\u0101jumi nav iesp\u0113jami"
  name: "Nav avota kop\u0161"
NonFreeAdd:
  description: "\u0160\u012B lietotne veicina nebr\u012Bvus papildin\u0101jumus"
  name: "Nebr\u012Bvi papildin\u0101jumi"
NonFreeAssets:
  description: "\u0160\u012B lietotne satur nebr\u012Bvus l\u012Bdzek\u013Cus"
  name: "Nebr\u012Bvi l\u012Bdzek\u013Ci"
NonFreeDep:
  description: "\u0160\u012B lietotne ir atkar\u012Bga no cit\u0101m nebr\u012Bv\u0101\
    m lietotn\u0113m"
  name: "Nebr\u012Bvas atkar\u012Bbas"
NonFreeNet:
  description: "\u0160\u012B lietotne veicina vai ir piln\u012Bgi atkar\u012Bga no\
    \ t\u012Bkla pakalpojuma, kas izmanto nebr\u012Bvo programmat\u016Bru"
  name: "Nebr\u012Bvi t\u012Bkla pakalpojumi"
TetheredNet:
  description: "\u0160\u012B lietotne ir piln\u012Bb\u0101 atkar\u012Bga no noteikta\
    \ veida t\u012Bkla pakalpojuma"
  name: "Piesaist\u012Bti t\u012Bkla pakalpojumi"
Tracking:
  description: "\u0160\u012B lietotne izseko darb\u012Bbas un zi\u0146o par t\u0101\
    m"
  name: "Izseko\u0161ana"
