AI Chat:
  name: AI Chat
App Manager:
  name: App Manager
App Store & Updater:
  name: App Store en Updater
Bookmark:
  name: Bladwijzer
Browser:
  name: Browser
Calculator:
  name: Rekenmachine
Calendar & Agenda:
  name: Kalender & Agenda
Clock:
  name: Klok
Cloud Storage & File Sync:
  name: Cloud opslag & Bestand Synchronisatie
Connectivity:
  name: Connectiviteit
Contact:
  name: Contact
DNS & Hosts:
  name: DNS & Hosts
Development:
  name: Ontwikkeling
Draw:
  name: Teken
Ebook Reader:
  name: Ebook lezer
Email:
  name: E-mail
File Encryption & Vault:
  name: Bestanden versleuteling en kluis
File Transfer:
  name: Bestandsoverdracht
Finance Manager:
  name: Financieel manager
Firewall:
  name: Firewall
Forum:
  name: Forum
Gallery:
  name: Galerij
Graphics:
  name: Grafisch
Habit Tracker:
  name: Gewoonte tracker
Icon Pack:
  name: Pictogrammenpakket
Internet:
  name: Internet
Inventory:
  name: Voorraad
Keyboard & IME:
  name: Toetsenbord en IME
Launcher:
  name: Launcher
Local Media Player:
  name: Lokale mediaspeler
Location Tracker & Sharer:
  name: Locatietracker en -deler
Messaging:
  name: Berichten
Multimedia:
  name: Multimedia
Music Practice Tool:
  name: Muziek oefentool
Navigation:
  name: Navigatie
Network Analyzer:
  name: Netwerk analysetool
News:
  name: Nieuws
Note:
  name: Notitie
Pass Wallet:
  name: Kaarten portemonnee
Password & 2FA:
  name: Wachtwoord en 2FA
Phone & SMS:
  name: Telefoon & SMS
Podcast:
  name: Podcast
Public Transport:
  name: Openbaar vervoer
Reading:
  name: Lezen
Recipe Manager:
  name: Receptenbeheerder
Religion:
  name: Religie
Science & Education:
  name: Onderwijs & wetenschap
Security:
  name: Beveiliging
Shopping List:
  name: Boodschappenlijst
Social Network:
  name: Sociaalnetwerk
Sports & Health:
  name: Sport & Gezondheid
System:
  name: Systeem
Task:
  name: Taak
Text Editor:
  name: Teksteditor
Theming:
  name: "Thema\u2019s"
Writing:
  name: Schrijven
