Ads:
  description: "Esta aplicaci\xF3n tiene publicidad"
  name: Anuncios
DisabledAlgorithm:
  description: "Esta aplicaci\xF3n tiene una firma de seguridad muy d\xE9bil"
  name: Firmado con un algoritmo inseguro
KnownVuln:
  description: "Esta aplicaci\xF3n contiene una vulnerabilidad de seguridad conocida"
  name: Vulnerabilidad conocida
NoSourceSince:
  description: "El c\xF3digo fuente ya no est\xE1 disponible, por lo que no tendr\xE1\
    \ versiones nuevas"
  name: "C\xF3digo no disponible desde"
NonFreeAdd:
  description: "Esta aplicaci\xF3n promueve complementos no libres"
  name: Complementos no libres
NonFreeAssets:
  description: "Esta aplicaci\xF3n contiene datos, im\xE1genes o textos que no son\
    \ libres"
  name: Elementos no libres
NonFreeDep:
  description: "Esta aplicaci\xF3n depende de otras que no son libres"
  name: Dependencias no libres
NonFreeNet:
  description: "Esta aplicaci\xF3n promueve o se conecta a servidores remotos que\
    \ no son libres"
  name: Servicios de red no libres
TetheredNet:
  description: "Esta aplicaci\xF3n depende de que un \xFAnico servidor remoto de un\
    \ tercero est\xE9 activo para funcionar"
  name: "Unido a un \xFAnico servicio de red"
Tracking:
  description: "Esta aplicaci\xF3n sigue lo que haces e informa de tu actividad"
  name: Rastreo y seguimiento
