Ads:
  description: Appen inneheld reklame
DisabledAlgorithm:
  description: Appen har ein svak tryggleikssignatur
KnownVuln:
  description: "Appen inneheld eit kjent tryggleiksh\xF2l"
NoSourceSince:
  name: "Kjeldekoden er ikkje lenger tilgjengeleg, s\xE5 det er ikkje mogleg med oppdatering."
NonFreeAdd:
  description: "Appen marknadsf\xF8rer ufrie tillegg"
NonFreeAssets:
  description: Appen inneheld ufrie ressursar
NonFreeDep:
  description: Appen er avhengig av andre ufrie appar
NonFreeNet:
  description: "Appen marknadsf\xF8rer ufrie nett-tenester"
Tracking:
  description: Denne appen sporar og rapporterer aktiviteten din
