Bookmark:
  name: Lieszeechen
Browser:
  name: Browser
Connectivity:
  name: Connectioun
Development:
  name: "Entw\xE9cklung"
Email:
  name: E-Mail
Forum:
  name: Forum
Gallery:
  name: Galerie
Graphics:
  name: Grafik
Internet:
  name: Internet
Multimedia:
  name: Multimedia
Navigation:
  name: Navigatioun
News:
  name: Noriichten
Note:
  name: Notiz
Phone & SMS:
  name: Telefon & SMS
Podcast:
  name: Podcast
Public Transport:
  name: "\xCBffentlechen Transport"
Reading:
  name: Liesen
Science & Education:
  name: "W\xEBssenschaft & Bildung"
Security:
  name: "S\xE9cherheet"
Sports & Health:
  name: Sport & Gesondheet
System:
  name: System
Writing:
  name: Schreiwen
