Ads:
  description: "Aplica\u021Bia con\u021Bine reclam\u0103"
  name: Reclame
DisabledAlgorithm:
  description: "Aplica\u021Bia are o semn\u0103tur\u0103 slab securizat\u0103"
  name: "Algoritm nesigur semn\u0103tur\u0103"
KnownVuln:
  description: "Aplica\u021Bia con\u021Bine o vulnerabilitate de securitate cunoscut\u0103"
  name: "Vulnerabilitate cunoscut\u0103"
NoSourceSince:
  description: "Codul surs\u0103 nu mai este disponibil, nu mai exist\u0103 posibilitatea\
    \ de a actualiza"
  name: "Nicio Surs\u0103 Din"
NonFreeAdd:
  description: "Aplica\u021Bia promoveaz\u0103 anexe ce nu sunt software liber"
  name: Anexe ne-libere
NonFreeAssets:
  description: "Aceasta aplica\u021Bie con\u021Bine resurse ce nu sunt la disponibile\
    \ la liber"
  name: Resurse ne-libere
NonFreeDep:
  description: "Aplica\u021Bia depinde de alte aplica\u021Bii ce nu sunt software\
    \ liber"
  name: "Dependen\u021Be ne-libere"
NonFreeNet:
  description: "Aplica\u021Bia promoveaz\u0103 sau depinde \xEEn \xEEntregime de un\
    \ serviciu de re\u021Bea care nu este liber"
  name: "Servicii de re\u021Bea ne-libere"
TetheredNet:
  description: "Aceast\u0103 aplica\u021Bie depinde \xEEn \xEEntregime de o anumit\u0103\
    \ instan\u021B\u0103 a unui serviciu de re\u021Bea"
  name: "Servicii de re\u021Bea captive"
Tracking:
  description: "Aplica\u021Bia \xEE\u021Bi \xEEnregistreaz\u0103 \u0219i raporteaz\u0103\
    \ activitatea undeva"
  name: "Urm\u0103rire"
