AI Chat:
  description: "Asisten\u021Bi AI, chatbo\u021Bi \u0219i interfe\u021Be bazate pe\
    \ modele lingvistice de mari dimensiuni (LLM)"
  name: Chat AI
Action Game:
  description: "Jocuri de ac\u021Biune, sport, curse \u0219i platform\u0103"
  name: "Joc de ac\u021Biune"
Alarm Clock:
  description: "Seteaz\u0103 alarma la or\u0103"
  name: "Alarm\u0103 ceas"
App Manager:
  description: "Gestionarea, organizarea \u0219i controlul aplica\u021Biilor instalate,\
    \ inten\u021Biile, permisiunile"
  name: "Manager aplica\u021Bii"
App Store & Updater:
  description: "Descoperirea, instalarea \u0219i actualizarea aplica\u021Biile din\
    \ depozitele software"
  name: "Magazin aplica\u021Bii & Actualiz\u0103ri"
Battery:
  description: "Monitorizarea \u0219i optimizarea duratei de via\u021B\u0103 a bateriei,\
    \ a utiliz\u0103rii \u0219i a \xEEnc\u0103rc\u0103rii"
  name: Baterie
Board Game:
  description: "Joc de societate, \u0219ah, Go, X \u0219i 0"
  name: Joc de societate
Bookmark:
  description: "Salvarea, organizarea \u0219i gestionarea link-uri preferate \u0219\
    i liste de lectur\u0103"
  name: Semn de carte
Browser:
  description: "Browsere web pentru navigare pe internet \u0219i vizualizare site-uri\
    \ web"
  name: Navigator web
Calculator:
  description: "Instrumente de calcul aritmetice, \u0219tiin\u021Bifice \u0219i matematice"
  name: Calculator
Calendar & Agenda:
  description: "Programare evenimente, memento-uri, \xEEnt\xE2lniri \u0219i planificare\
    \ de zi cu zi"
  name: "Calendar \u0219i agenda"
Camera:
  description: "Camera, vizualizatorul camerei IP \u0219i \xEEnregistrarel video"
  name: Camera foto
Card Game:
  description: "Joc de c\u0103r\u021Bi, solitaire"
  name: "Joc de c\u0103r\u021Bi"
Cast:
  description: Transmisie, oglindire, UPnP, DLNA, FCast, AirPlay, Miracast
  name: Difuzare
Casual Game:
  description: Joc simplu de ocazie
  name: Joc ocazional
Clock:
  description: "Arat\u0103 ora curent\u0103"
  name: Ceas
Cloud Storage & File Sync:
  description: "Copii de siguran\u021B\u0103, sincronizare \u0219i accesare de la\
    \ distan\u021B\u0103 prin intermediul serviciilor online"
  name: "Stocare \xEEn cloud & Sincronizare fi\u0219iere"
Code & Forge:
  description: "Git, g\u0103zduire de cod surs\u0103"
  name: "Depozit cod surs\u0103"
Connectivity:
  name: Conectivitate
Contact:
  description: "Agend\u0103 persoane, list\u0103 de contacte \u0219i gestionarea contactelor"
  name: Contact
DNS & Hosts:
  description: "Configurare serverele DNS, blocarea reclamelor, fi\u0219ierul hosts\
    \ \u0219i rutarea domeniilor"
  name: DNS & Gazde
Development:
  description: "Cod, programare, IDE, terminal \u0219i instrumente pentru dezvoltatori"
  name: Dezvoltare programe
Dice:
  description: Selector aleator
  name: Zar
Diet:
  description: "Nutri\u021Bie, calorii, managementul \u0219i urm\u0103rirea alimentelor"
  name: "Diet\u0103"
Download:
  description: "Desc\u0103rc\u0103tor, manager de desc\u0103rcare \u0219i client torrent"
  name: "Desc\u0103rcare"
Draw:
  description: "Schi\u021Be, pictur\u0103, ilustra\u021Bie, canava \u0219i art\u0103\
    \ digital\u0103"
  name: Desen
Ebook Reader:
  description: "Cititor c\u0103r\u021Bi electronice, EPUB, PDF \u0219i c\u0103r\u021B\
    i \u0219i publica\u021Bii digitale"
  name: "Carte electronic\u0103"
Educational Game:
  description: "\xCEnva\u021B\u0103 \xEEn joc, test, chestionar, concurs"
  name: "Joc educa\u021Bional"
Email:
  description: "Clien\u021Bii de trimis \u0219i primit e-mail \u0219i gestionarea\
    \ mesajelor prin e-mail"
  name: E-mail
Emulator:
  description: "Emulator de joc \u0219i program"
  name: Emulator
File Encryption & Vault:
  description: "Criptare, blocare \u0219i ascundere fi\u0219iere \u0219i dosarele\
    \ private"
  name: "Criptare fi\u0219iere \u0219i seif"
File Manager:
  description: "Manager de fi\u0219iere \u0219i explorator"
  name: "Manager fi\u0219ier"
File Transfer:
  description: "Partajare \u0219i transfer fi\u0219iere prin FTP, LAN, Bluetooth sau\
    \ peer-to-peer (p2p)"
  name: "Transfer fi\u0219iere"
Finance Manager:
  description: "Urm\u0103rirea cheltuieli, bugete, venituri \u0219i conturi financiare\
    \ personale"
  name: Manager financiar
Firewall:
  description: "Blocare traficul nedorit de re\u021Bea \u0219i control acces la Internet"
  name: Firewall
Flashlight:
  description: "Lantern\u0103 \u0219i bli\u021B cu LED"
  name: "Lantern\u0103"
Forum:
  description: "Forumuri de discu\u021Bii, grupuri comunitare \u0219i platforme de\
    \ \xEEntreb\u0103ri \u0219i r\u0103spunsuri"
  name: Forum
Gallery:
  description: "Navigare, vizualizare \u0219i organizare fotografii, imagini \u0219\
    i videoclipuri"
  name: Galerie
Game Helper:
  description: Ajutor de joc, asistent, tabela de scor, cronometrul
  name: Instrument de ajutor pentru joc
Graphics:
  description: "Editare imagini, manipulare fotografii \u0219i instrumentele de design\
    \ vizual"
  name: "Grafic\u0103"
Habit Tracker:
  description: "Construire rutine, urm\u0103rire obiective zilnice \u0219i monitorizare\
    \ seriile personale"
  name: Jurnal de obiceiuri
Health Manager:
  description: "Management greutate, ritmul cardiac, tensiunea arterial\u0103, menstrua\u021B\
    ia \u0219i alte m\u0103sur\u0103tori de s\u0103n\u0103tate"
  name: "Manager de s\u0103n\u0103tate"
Icon Pack:
  description: "Seturi de pictograme personalizate \u0219i tematice"
  name: "Pachet iconi\u021Be"
Internet:
  name: Internet
Inventory:
  description: "Urm\u0103rire, catalogare \u0219i gestionare elementele fizice \u0219\
    i stocuri"
  name: Inventar
Keyboard & IME:
  description: "Tastaturi personalizate, metode de introducere, autocorectare \u0219\
    i tastare"
  name: "Tastatur\u0103 & IME"
Launcher:
  description: "Personalizare ecran de start, lansator \u0219i a mediului de lucru"
  name: Lansator
Local Media Player:
  description: "Redare fi\u0219ierele audio \u0219i video stocate pe dispozitiv"
  name: Vizualizator media local
Location Tracker & Sharer:
  description: "Partajare \u0219i monitorizare loca\u021Bie GPS \xEEn timp real cu\
    \ al\u021Bii"
  name: "Localizare \u0219i partajare loca\u021Bie"
Lyrics:
  description: "Vizualizare \u0219i c\u0103utare versuri"
  name: Versuri
Market & Price:
  description: "Curs de schimb, pia\u021B\u0103 \u0219i stoc"
  name: "Comer\u021B \u0219i pre\u021B"
Meditation:
  description: "Medita\u021Bie, mindfulness, practic\u0103 de respira\u021Bie"
  name: "Medita\u021Bie"
Messaging:
  description: "Mesagerie instantanee, discu\u021Bii, SMS \u0219i comunicare"
  name: Mesagerie
Multimedia:
  name: Multimedia
Music Practice Tool:
  description: "Tunerele, metronom, uneltele de coard\u0103 \u0219i ajutoarele pentru\
    \ practicarea instrumentelor"
  name: "Instrumentul de practic\u0103 muzical\u0103"
Navigation:
  description: "H\u0103r\u021Bi, GPS, direc\u021Bii pas cu pas \u0219i planificare\
    \ rute"
  name: "Naviga\u021Bie"
Network Analyzer:
  description: "Diagnosticare Wi-Fi, scanare re\u021Bele \u0219i monitorizarea performan\u0163\
    ei conexiunii"
  name: "Analiz\u0103 re\u021Bea"
News:
  description: "Cele mai recente titluri, articole, fluxuri RSS \u0219i agregatoare\
    \ de \u0219tiri"
  name: "\u0218tiri"
Note:
  description: "Agende, memoriu \u0219i luarea rapid\u0103 de noti\u021Be \u0219i\
    \ organizare"
  name: "Noti\u021Be"
Notification:
  description: "Manager de notificare, jurnalizare, redirec\u021Bionare, \xEEmbun\u0103\
    t\u0103\u021Bire"
  name: Notificare
OCR:
  description: "Scaner de documente, recunoa\u0219tere optic\u0103 a caracterelor"
  name: OCR
Online Media Player:
  description: "Redare muzic\u0103, videoclipuri \u0219i con\u021Binut \xEEn direct\
    \ de pe Internet"
  name: Vizualizator media pe Internet
Party Game:
  description: "Mai mul\u021Bi juc\u0103tori, joc de petrecere"
  name: Joc de petrecere
Pass Wallet:
  description: "Stocare permise de \xEEmbarcare, bilete, carduri de loialitate \u0219\
    i cupoane"
  name: Portofel tichete
Password & 2FA:
  description: "Manager de parole, autentificator, OTP, TOTP, HOTP, U2F, FIDO \u0219\
    i instrumente de securitate cu doi factori"
  name: Parole & 2FA
Phone & SMS:
  description: "Aplica\u021Bii de apelare, gestionare a apelurilor \u0219i mesagerie\
    \ text"
  name: Telefon & SMS
Platformer Game:
  description: "Platformer, joc de derulare lateral\u0103"
  name: Joc platformer
Podcast:
  description: "Abonare, ascultare \xEEn flux \u0219i desc\u0103rcare episoade \u0219\
    i emisiuni audio de podcast"
  name: Podcast
Public Transport:
  description: "Autobuz, tren, metrou, ore de tranzit \u0219i planificatoare de c\u0103\
    l\u0103torie"
  name: Transport public & Orar
Push:
  description: Mesaje push
  name: Push
Puzzle Game:
  description: Puzzle, sudoku, joc de memorie
  name: Jocuri de puzzle
Radio:
  description: "Ascultare \xEEn direct posturi de radio FM/AM \u0219i transmisiuni\
    \ radio pe internet"
  name: Radio
Reading:
  description: "Articole, con\u021Binut cu form\u0103 lung\u0103, cite\u0219te mai\
    \ t\xE2rziu \u0219i cititor web"
  name: Citit
Recipe Manager:
  description: "Salvare, organizare \u0219i descoperire re\u021Bete de g\u0103tit\
    \ \u0219i idei de meniu"
  name: "Manager re\u021Bete"
Recorder:
  description: "Microfon, ecran, \xEEnregistrare apel"
  name: "\xCEncegistrare audio"
Religion:
  description: "Ore de rug\u0103ciune, texte sfinte, devo\u021Bionale \u0219i practic\u0103\
    \ spiritual\u0103"
  name: Religie
Remote Access:
  description: "Control desktop-uri, servere \u0219i dispozitive de la distan\u021B\
    \u0103 prin RDP, VNC sau SSH"
  name: "Acces la distan\u021B\u0103"
Remote Controller:
  description: "Infra-ro\u0219u \u0219i telecomenzi de cas\u0103 inteligente pentru\
    \ televizoare, unit\u0103\u021Bi AC \u0219i alte dispozitive"
  name: "Control la distan\u021B\u0103"
Role-Playing Game:
  description: Joc de aventura, explorare, rogue-like
  name: Joc de rol
Schedule:
  description: "Programul conferin\u021Belor \u0219i evenimentelor"
  name: Planificare
Science & Education:
  description: "\xCEnv\u0103\u021Bare, studiu, consultare \u0219i educa\u021Bie"
  name: "\u0218tiin\u021B\u0103 & educa\u021Bie"
Security:
  name: Securitate
Shooter Game:
  description: "Antrenamente la \u021Bint\u0103, tir cu arme"
  name: "Joc cu \xEEmpu\u0219c\u0103turi"
Shopping List:
  description: "Liste de cump\u0103r\u0103turi, urm\u0103rirea produselor de cump\u0103\
    rat \u0219i cump\u0103r\u0103turi colaborative"
  name: "List\u0103 cump\u0103r\u0103turi"
Social Network:
  description: "Social media, microblogging \u0219i platformele comunit\u0103\u021B\
    ilor online"
  name: "Re\u021Bea social\u0103"
Sport Game:
  description: Jocuri de sport, atletice, reflex
  name: Joc sportiv
Sports & Health:
  description: "Monitorizarea activit\u0103\u021Bii fizice, starea de bine, rezultate\
    \ sportive \u0219i monitorizarea st\u0103rii de s\u0103n\u0103tate"
  name: "Sport & s\u0103n\u0103tate"
Stopwatch:
  description: "M\u0103surarea progresului, timp scurs, cronometru de tur"
  name: Cronometru
Strategy Game:
  description: Strategie, simulare
  name: Joc de strategie
System:
  name: Sistem
Task:
  description: "Liste de sarcini, gestionarea activit\u0103\u021Bilor, instrumente\
    \ de productivitate \u0219i GTD"
  name: Activitate
Text Editor:
  description: "Editor text neformatat, Markdown \u0219i instrumente de scriere"
  name: Editor text
Text to Speech:
  description: Instrumente TTS
  name: "Conversie text \xEEn vorbire"
Theming:
  description: "Personalizare aspect dispozitiv cu teme, fonturi \u0219i stiluri de\
    \ interfa\u021B\u0103"
  name: Teme
Time Tracker:
  description: "Urm\u0103ri\u021Bi utilizarea timpului pe activit\u0103\u021Bi \u0219\
    i timpul petrecut \xEEn fa\u021Ba ecranului"
  name: "Urm\u0103rirea timpului"
Timer:
  description: "Temporizare interval, pontaj, num\u0103r\u0103toarea invers\u0103"
  name: Temporizator
Translation & Dictionary:
  description: "Traducerea limbilor, c\u0103utare cuvinte \u0219i accesare vocabular\
    \ referin\u021Be"
  name: "Traducere & dic\u021Bionar"
Unit Convertor:
  description: "Conversie \xEEntre unit\u0103\u021Bi de lungime, greutate, temperatur\u0103\
    , valut\u0103 \u0219i multe altele"
  name: "Convertor unit\u0103\u021Bi"
VPN & Proxy:
  description: "Criptare trafic, ocolire restric\u021Biile (eludare) \u0219i anonimizare\
    \ conexiune"
  name: "VPN \u0219i proxy"
Visual Novel:
  description: Roman vizual, joc de poveste
  name: Romanul vizual
Voice & Video Chat:
  description: "Apelare audio \u0219i video, conferin\u021Be \u0219i comunicare VoIP"
  name: Apeluri audio & Video
Volume:
  description: "Configureaz\u0103 set\u0103ri volum"
  name: Volum audio
Wallet:
  description: "Portofele digitale pentru pl\u0103\u021Bi, carduri \u0219i gestionarea\
    \ criptomonedelor"
  name: Portofel
Wallpaper:
  description: "Fundalul ecranului de start, al ecranului de blocare \u0219i fundaluri\
    \ animate"
  name: Fundal
Weather:
  description: "Previziuni, radar, temperaturi \u0219i condi\u021Bii atmosferice"
  name: Meteo
Word Game:
  description: "Joc de puzzle cu cuvinte, cuvinte \xEEncruci\u0219ate, ghicire a cuvintelor"
  name: Joc de cuvinte
Workout:
  description: "Rutine de exerci\u021Bii, monitorizarea activit\u0103\u021Bii la sal\u0103\
    , alergare \u0219i antrenament de fitness"
  name: Antrenament
Writing:
  description: "Procesare text, jurnalizare, redactare schi\u021Be \u0219i aplica\u021B\
    ii de scriere \xEEn form\u0103 lung\u0103"
  name: Scris
