Ads:
  description: "Esta aplicaci\xF3n cont\xE9n publicidade"
  name: Anuncios
DisabledAlgorithm:
  description: "Esta aplicaci\xF3n ten unha sinatura de seguranza feble"
  name: Asinado usando un algoritmo inseguro
KnownVuln:
  description: "Esta aplicaci\xF3n cont\xE9n unha vulnerabilidade de seguranza co\xF1\
    ecida"
  name: "Vulnerabilidade Co\xF1ecida"
NoSourceSince:
  description: "O c\xF3digo fonte xa non est\xE1 dispo\xF1ible, non recibir\xE1 actualizaci\xF3\
    ns"
  name: "Sen acceso ao c\xF3digo desde"
NonFreeAdd:
  description: "Esta aplicaci\xF3n promociona engadidos que non son libres ou de balde"
  name: Complementos non libres
NonFreeAssets:
  description: "Esta aplicaci\xF3n cont\xE9n elemento non libres"
  name: Activos non libres
NonFreeDep:
  description: "Esta aplicaci\xF3n depende doutras aplicaci\xF3ns non libres"
  name: Dependencias non libres
NonFreeNet:
  description: "Esta aplicaci\xF3n promove servizos de rede que non son libres"
  name: Servizos de rede non libres
TetheredNet:
  description: Esta app depende totalmente dunha determinada instancia dun servizo
    da rede
  name: "Servizos de rede con f\xEDos"
Tracking:
  description: "Esta aplicaci\xF3n rexistra e informa da t\xFAa actividade"
  name: Seguimento
