workflow:
  rules:
    # required to enable merge request pipelines: https://docs.gitlab.com/ee/ci/pipelines/merge_request_pipelines.html#prerequisites
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_ENABLE_MERGE_REQUEST_PIPELINES != "false"
    # to prevent duplicate pipelines in MRs: https://docs.gitlab.com/ee/ci/yaml/workflow.html#switch-between-branch-pipelines-and-merge-request-pipelines
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push" && $CI_ENABLE_MERGE_REQUEST_PIPELINES != "false"
      when: never
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

stages:
  - build
  - test

variables:
  pip: pip3 --timeout 100 --retries 10

  GIT_DEPTH:
    description: needs lots of git history since it has to compare the merge request to current master
    value: "5000"

  CI_ENABLE_MERGE_REQUEST_PIPELINES:
    description: push with `git push -o ci.variable="CI_ENABLE_MERGE_REQUEST_PIPELINES=false"` to disable merge request pipelines (e.g., to use self-hosted runners)
    value: "true"

.install_fdroid_server: &install_fdroid_server
  - rm -rf $fdroidserver
  - mkdir $fdroidserver
  - git ls-remote https://gitlab.com/fdroid/fdroidserver.git master
  - curl --silent https://gitlab.com/fdroid/fdroidserver/-/archive/master/fdroidserver-master.tar.gz
        | tar -xz --directory=$fdroidserver --strip-components=1
  - export PATH="$fdroidserver:$PATH"
  - export PYTHONPATH="$fdroidserver:$fdroidserver/examples"
  - export PYTHONUNBUFFERED=true
  # avoid error from the env var in config.yml
  - export serverwebroot=/tmp

.install_fdroid_server_deb: &install_fdroid_server_deb
  - apt-get --allow-releaseinfo-change update
  - apt-get -qy dist-upgrade
  - echo "locales locales/locales_to_be_generated multiselect en_US.UTF-8 UTF-8" | debconf-set-selections
  - apt-get install -qy --no-install-recommends fdroidserver apksigner mercurial git git-svn brz python3-launchpadlib locales curl

.set_up_test_keystore: &set_up_test_keystore
  - cp -a $fdroidserver/tests/gnupghome $fdroidserver/tests/keystore.jks $CI_PROJECT_DIR/
  - grep '^key.*pass' $fdroidserver/tests/config.yml | sed 's,\x3a ,=,' > $CI_PROJECT_DIR/variables
  - |
    tee --append $CI_PROJECT_DIR/variables <<EOF
        gpghome=$CI_PROJECT_DIR/gnupghome
        keystore=$CI_PROJECT_DIR/keystore.jks
        serverwebroot=/tmp
        export gpghome keypass keystorepass keystore serverwebroot
    EOF
  - source $CI_PROJECT_DIR/variables
  # silence warnings
  - chmod 0600 config.yml config/*.yml config/*/*.yml
  - chmod 0700 $gpghome
  # make fake 'ciarang' index signing key
  - keytool -keyclone -alias 4e7da5b7 -dest ciarang
        -keypass:env keypass -new:env keypass -storepass:env keystorepass -keystore $keystore
  - sed -i 's,^\(gpgkey\x3a\).*,\1 F9A6B8DF7566FCAB173AAB3516D6C4D3CE71F7FB,' config.yml

.get_target_source_refs: &get_target_source_refs
  - |
    if [ "$CI_PROJECT_PATH" = "fdroid/fdroiddata" ] && [ "$CI_COMMIT_BRANCH" = "$CI_DEFAULT_BRANCH" ]; then
        export TARGET_REF="${CI_COMMIT_BEFORE_SHA}"
        export SOURCE_REF="${CI_COMMIT_SHA}"
    else
        git remote add upstream https://gitlab.com/fdroid/fdroiddata.git || true
        git fetch upstream ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:-master}
        export TARGET_REF=$(git merge-base HEAD upstream/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:-master})
        export SOURCE_REF="${CI_COMMIT_SHA}"
    fi;

.get_changed_builds: &get_changed_builds
  - *get_target_source_refs
  - echo $TARGET_REF
  - |
    for f in $(git diff --name-only --diff-filter=d "${TARGET_REF}...${SOURCE_REF}" -- metadata/*.yml) $(git diff --name-only --diff-filter=d "${TARGET_REF}...${SOURCE_REF}" -- metadata/*/signatures); do
        diff=$(git diff "${TARGET_REF}...${SOURCE_REF}" -- "$f")
        echo "$diff"
        test $(echo "$diff" | perl -wnle '/^[+-](( +-)|( *\w))/ and print' | grep -v -c '^+ *disable:') = 0 && continue
        echo "$diff" | grep -E '^\+ *(NoSourceSince|Disabled):' && continue
        appid=$(echo "$f" | sed -E -n 's,^metadata/([^/][^/]*)(\.yml|/signatures/.*),\1,p')
        export CHANGED="$CHANGED $appid"
    done

.get_changed_apps: &get_changed_apps
  - *get_target_source_refs
  - echo $TARGET_REF
  - |
    for f in $(git diff --name-only --diff-filter=d "${TARGET_REF}...${SOURCE_REF}" -- metadata/*.yml) $(git diff --name-only --diff-filter=d "${TARGET_REF}...${SOURCE_REF}" -- metadata/*/signatures); do
        diff=$(git diff "${TARGET_REF}...${SOURCE_REF}" -- "$f")
        appid=$(echo "$f" | sed -E -n 's,^metadata/([^/][^/]*)(\.yml|/signatures/.*),\1,p')
        export CHANGED="$CHANGED $appid"
    done

.app_verification_rules:
  rules: &app_verification_rules
    - if: $CI_PIPELINE_SOURCE == "pipeline" || $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "trigger"
      when: never
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_ENABLE_MERGE_REQUEST_PIPELINES != "false"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      # only works for merge request pipelines: https://docs.gitlab.com/ee/ci/jobs/job_control.html#jobs-or-pipelines-run-unexpectedly-when-using-changes
      changes:
        - metadata/**/*
        - srclibs/**/*
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

checkupdates:
  stage: test
  needs: []
  image: debian:trixie-slim
  rules: *app_verification_rules
  before_script:
    - *install_fdroid_server_deb
    - export fdroidserver=../fdroidserver
    - *install_fdroid_server
  script:
    - |
      set -xe
    - chown -R $(whoami) .
    - *get_changed_builds
    - |
      if [ -n "$CHANGED" ]; then
        fdroid checkupdates --auto -v $CHANGED
        if [[ -n $(git diff --name-only) ]]; then
          git config user.name "GitLab CI"
          git config user.email "ci@gitlab.com"
          git add .
          git commit -m "Auto-fix from checkupdates"
          git push https://project-creator:glpat-SPCeYBGKIg2uRP8yQGetGmM6MQpvOjEKdTpvMHk4cA8.01.171vwtsm1@gitlab.com/${CI_PROJECT_PATH}.git HEAD:${CI_COMMIT_REF_NAME} || exit 1
        fi
      fi

git redirect:
  stage: test
  needs: []
  image: debian:trixie-slim
  rules: *app_verification_rules
  script:
    - apt-get -qy update
    - apt-get -qy dist-upgrade
    - apt-get -qy install --no-install-recommends ca-certificates git python3 python3-yaml
    - chown -R $(whoami) .
    - *get_changed_apps
    - test -n "$CHANGED" || exit 0
    - tools/rewrite-git-redirects.py $CHANGED
    - |
      if [[ -n $(git diff --name-only) ]]; then
        git config user.name "GitLab CI"
        git config user.email "ci@gitlab.com"
        git add .
        git commit -m "Auto-fix from git redirect"
        git push https://project-creator:glpat-SPCeYBGKIg2uRP8yQGetGmM6MQpvOjEKdTpvMHk4cA8.01.171vwtsm1@gitlab.com/${CI_PROJECT_PATH}.git HEAD:${CI_COMMIT_REF_NAME} || exit 1
      fi
  artifacts:
    reports:
      codequality: codequality.json

tools check scripts:
  stage: test
  needs: []
  image: debian:trixie-slim
  rules: *app_verification_rules
  script:
    - apt-get -qy update
    - apt-get -qy dist-upgrade
    - apt-get -qy install --no-install-recommends exiftool git jq python3 python3-yaml
    - export EXITVALUE=0
    - function set_error() { export EXITVALUE=1; printf "\x1b[31mERROR `history|tail -2|head -1|cut -b 6-500`\x1b[0m\n"; }

    - chown -R $(whoami) .
    - ./tools/check-exif-in-images.sh || true
    - ./tools/check-localized-metadata.py || set_error
    - ./tools/check-keyalias-collision.py || set_error
    - ./tools/check-metadata-summary-whitespace.py || set_error
    - ./tools/check-for-unattached-signatures.py || set_error
    - ./tools/make-summary-translatable.py || true

    - |
      if [[ -n $(git diff --name-only) ]]; then
        git config user.name "GitLab CI"
        git config user.email "ci@gitlab.com"
        git add .
        git commit -m "Auto-fix from tools check scripts"
        git push https://project-creator:glpat-SPCeYBGKIg2uRP8yQGetGmM6MQpvOjEKdTpvMHk4cA8.01.171vwtsm1@gitlab.com/${CI_PROJECT_PATH}.git HEAD:${CI_COMMIT_REF_NAME} || set_error
      fi

    # GitLab only supports one codequality report per job
    - jq '[.[]|.[]]' --slurp *.json > codequality.json

    - exit $EXITVALUE
  artifacts:
    reports:
      codequality: codequality.json


# Use roundtrip parsing to check whether config file is in the
# strictest subset of YAML 1.2 format, aka the JSON Schema.  YAML 1.2
# supports truth values like True and TRUE under the "Core Schema".
# All values in config files should match in the JSON schema to avoid
# type confusion.
#
# https://yaml.org/spec/1.2.2/#example-json-tag-resolution
#
# yq does not preserve blank lines or comments, so those are removed
# from the comparison.
YAML 1.2:
  stage: test
  needs: []
  image: debian:trixie-slim
  rules:
    - changes:
        paths:
          - .gitlab-ci.yml
          - config.yml
          - config/*.yml
          - config/*/*.yml
  script:
    - apt-get -qy update
    - apt-get -qy install --no-install-recommends python3-yaml yq
    - chown -R $(whoami) .
    - |
      for f in config.yml config/*.yml config/*/*.yml; do
          test -f $f || continue
          python3 -c "import yaml; yaml.dump(yaml.load(open('$f'), Loader=yaml.SafeLoader), open('canonical.yml', 'w'))"
          yq --output-format json canonical.yml > canonical.json
          yq --output-format json $f > current.json
          diff -u canonical.json current.json || {
              printf "\x1b[31mERROR $f is not YAML 1.2 JSON Schema compliant!\x1b[0m\n";
              exit 1;
          }
      done


fdroid lint:
  stage: test
  needs: []
  image: debian:trixie-slim
  rules: *app_verification_rules
  before_script:
    - *install_fdroid_server_deb
    - export fdroidserver=$PWD/fdroidserver
    - *install_fdroid_server
  script:
    - chown -R $(whoami) .
    - *get_changed_apps
    - echo $CHANGED
    - fdroid lint $CHANGED


fdroid rewritemeta:
  stage: test
  needs: []
  image: debian:trixie-slim
  rules: *app_verification_rules
  artifacts:
    name: "${CI_PROJECT_PATH}_${CI_JOB_STAGE}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}"
    paths:
      - tmp/
    when: always
    expire_in: 1 week
  before_script:
    - *install_fdroid_server_deb
    - export fdroidserver=$PWD/fdroidserver
    - *install_fdroid_server
  script:
    - chown -R $(whoami) .
    - *get_changed_apps
    - |
      if [ -n "$CHANGED" ]; then
          fdroid rewritemeta $CHANGED;
          if [[ -n $(git diff --name-only) ]]; then
            git config user.name "GitLab CI"
            git config user.email "ci@gitlab.com"
            git add .
            git commit -m "Auto-fix from fdroid rewritemeta"
            git push https://project-creator:glpat-SPCeYBGKIg2uRP8yQGetGmM6MQpvOjEKdTpvMHk4cA8.01.171vwtsm1@gitlab.com/${CI_PROJECT_PATH}.git HEAD:${CI_COMMIT_REF_NAME} || exit 1
          fi
      fi


fdroid lint config:
  stage: test
  needs: []
  image: debian:trixie-slim
  rules:
    - changes:
        paths:
          - config.yml
          - config/*.yml
          - config/*/*.yml
  before_script:
    - *install_fdroid_server_deb
    - export fdroidserver=$PWD/fdroidserver
    - *install_fdroid_server
  script:
    - chown -R $(whoami) .
    - fdroid lint config.yml config/*.yml config/*/*.yml


schema validation:
  stage: test
  needs: []
  image: python
  rules: *app_verification_rules
  before_script:
    - pip install check-jsonschema
  script:
    - chown -R $(whoami) .
    - check-jsonschema --check-metaschema schemas/metadata.json || exit 1
    - *get_target_source_refs
    - git diff --exit-code --name-only "${TARGET_REF}...${SOURCE_REF}" schemas/metadata.json
          || { check-jsonschema --schemafile schemas/metadata.json metadata/*.yml || exit 1; exit; }
    - set -xe
    - *get_changed_apps
    - if [ -z "$CHANGED" ]; then exit; fi
    - |
      if [[ -n $(git diff --name-only) ]]; then
        git config user.name "GitLab CI"
        git config user.email "ci@gitlab.com"
        git add .
        git commit -m "Auto-fix from schema validation"
        git push https://project-creator:glpat-SPCeYBGKIg2uRP8yQGetGmM6MQpvOjEKdTpvMHk4cA8.01.171vwtsm1@gitlab.com/${CI_PROJECT_PATH}.git HEAD:${CI_COMMIT_REF_NAME} || exit 1
      fi
    - echo $CHANGED | sed -En 's|([^ ]*)|metadata/\1.yml|gp' | xargs check-jsonschema --schemafile schemas/metadata.json

# This job should be as close as possible to the production
# buildserver.  It should not include custom setup or methods, except
# when there is no other way to make this job work.  The docker image
# is created using the same provisioning as the production buildserver,
# via the "docker" job in fdroid/fdroidserver.
#
# This job is tied to the buildserver.  Changes must be reviewed by
# the buildserver maintainers.
fdroid build:
  stage: build
  needs: []
  tags:
    - saas-linux-medium-amd64
  # Some env vars are setup in https://gitlab.com/fdroid/fdroidserver/-/blob/master/buildserver/setup-env-vars
  # home_vagrant=/home/vagrant
  image: registry.gitlab.com/fdroid/fdroidserver:buildserver-trixie
  artifacts:
    name: "${CI_PROJECT_PATH}_${CI_JOB_STAGE}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}"
    paths:
      - repo/
      - unsigned/
      - tmp/
    when: always
    expire_in: 1 week
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .pub-cache/
  before_script:
    - *install_fdroid_server_deb
    - export fdroidserver=$PWD/fdroidserver
    - *install_fdroid_server
    - *set_up_test_keystore
  script:
    - export EXITVALUE=0
    - function set_error() { export EXITVALUE=1; printf "\x1b[31mERROR `history|tail -2|head -1|cut -b 6-500`\x1b[0m\n"; }
    - chown -R $(whoami) .
    - *get_changed_builds
    - |
      if [ -n "$CHANGED" ]; then
        for appid in $CHANGED; do
          fdroid build --verbose --scan-only $appid || set_error
          fdroid build --verbose --latest --no-sync $appid || set_error
        done
      fi
    - exit $EXITVALUE
