image: "ghcr.io/cirruslabs/flutter:stable"

variables:
  JAVA_VERSION: "21"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - .pub-cache/
    - build/

before_script:
  - export PATH="$PATH:$HOME/.pub-cache/bin"
  - flutter doctor
  - flutter pub get

build_foss_release:
  stage: build
  script:
    - flutter build apk --flavor foss --release || [ -f android/app/build/outputs/apk/foss/release/app-foss-release.apk ]
  artifacts:
    paths:
      - android/app/build/outputs/apk/foss/release/app-foss-release.apk
