Ads:
  description: Tha sanasachd am broinn na h-aplacaid seo
  name: Sanasachd
DisabledAlgorithm:
  description: "Tha soidhneadh t\xE8arainteachd lag aig an aplacaid seo"
  name: "Soidhneadh le algairim nach eil s\xE0bhailte"
KnownVuln:
  description: "Tha so-le\xF2ntachd t\xE8arainteachd aithnichte am broinn na h-aplacaid\
    \ seo"
  name: "So-le\xF2ntachd aithnichte"
NoSourceSince:
  name: "Chan eil am bun-t\xF9s ri fhaighinn tuilleadh is cha ghabh a h-\xF9rachadh."
NonFreeAdd:
  description: Brosnaichidh an aplacaid seo tuilleadain nach eil saor
  name: Tuilleadain neo-shaor
NonFreeAssets:
  description: Tha maoin nach eil saor am broinn na h-aplacaid seo
  name: Maoin neo-shaor
NonFreeDep:
  description: Tha an aplacaid seo an eisimeil air aplacaidean eile nach eil saor
  name: Eisimeileachdan neo-shaor
NonFreeNet:
  description: "Brosnaichidh an aplacaid seo seirbheisean l\xEConraidh nach eil saor"
  name: "Seirbheisean l\xEConraidh neo-shaor"
TetheredNet:
  description: "Tha an aplacaid seo a\u2019 brosnachadh no gu tur an eisimeil air\
    \ ionstans s\xF2nraichte de sheirbheis l\xEConraidh."
  name: "L\xEConra teadhraichte"
Tracking:
  description: "N\xEC an aplacaid seo tracadh ort is n\xEC i aithris air do ghn\xEC\
    omhachd"
  name: Tracadh
