Connectivity:
  name: Comas-ceangail
Development:
  name: Leasachadh
Graphics:
  name: Grafaigeachd
Internet:
  name: "Eadar-l\xECon"
Multimedia:
  name: Meadhanan
Navigation:
  name: "Se\xF2ladaireachd"
Phone & SMS:
  name: "F\xF2n \u204A SMS"
Reading:
  name: Leughadh
Science & Education:
  name: "Saidheans \u204A foghlam"
Security:
  name: "T\xE8arainteachd"
Sports & Health:
  name: "Sp\xF2rs \u204A sl\xE0inte"
System:
  name: An siostam
Theming:
  name: "\xD9rlaran"
Writing:
  name: "Sgr\xECobhadh"
