Ads:
  description: "Ky aplikacion p\xEBrmban reklama"
  name: Reklama
DisabledAlgorithm:
  description: "Ky aplikacion ka nj\xEB n\xEBnshkrim t\xEB dob\xEBt sigurie"
  name: "N\xEBnshkruar Duke P\xEBrdorur Nj\xEB Algorit\xEBm Jo t\xEB Parrezik"
KnownVuln:
  description: "Ky aplikacion p\xEBrmban nj\xEB cenueshm\xEBri t\xEB njohur sigurie"
  name: "Cenueshm\xEBri e Ditur"
NoSourceSince:
  description: "Kodi burim s\u2019mund t\xEB kihet m\xEB, s\u2019ka p\xEBrdit\xEB\
    sime t\xEB mundshme"
  name: "S\u2019ka Burime Q\xEB Prej"
NonFreeAdd:
  description: "Ky aplikacion rekomandon shtesa jo t\xEB lira"
  name: "Shtesa Jo t\xEB Lira"
NonFreeAssets:
  description: "Ky aplikacion p\xEBrmban element\xEB jo t\xEB lir\xEB"
  name: "Element\xEB Jo t\xEB Lir\xEB"
NonFreeDep:
  description: "Ky aplikacion varet nga aplikacione t\xEB tjera jo t\xEB lira"
  name: "Var\xEBsi Jo t\xEB Lira"
NonFreeNet:
  description: "Ky aplikacion promovon, ose varet t\xEBr\xEBsisht nga nj\xEB sh\xEB\
    rbim rrjeti jo t\xEB lir\xEB"
  name: "Sh\xEBrbime Rrjeti Jo t\xEB Lira"
TetheredNet:
  description: "Ky aplikacion varet t\xEBr\xEBsisht n\xEB nj\xEBfar\xEB instance t\xEB\
    \ nj\xEB sh\xEBrbimi rrjeti"
Tracking:
  description: "Ky aplikacion gjurmon dhe raporton veprimtarin\xEB tuaj"
  name: Gjurmim
