AI Chat:
  name: Fjalosje IA
App Manager:
  name: "P\xEBrgjegj\xEBs Aplikacionesh"
App Store & Updater:
  name: "Shitore & P\xEBrdit\xEBsues Aplikacionesh"
Battery:
  name: Bateri
Bookmark:
  name: "Faqerojt\xEBs"
Browser:
  name: Shfletues
Calculator:
  name: "Makin\xEB Llogarit\xEBse"
Calendar & Agenda:
  name: Kalendar & Plane
Clock:
  name: Sahat
Cloud Storage & File Sync:
  name: "Depozitim N\xEB Re & Nj\xEBkoh\xEBsim Kartelash"
Connectivity:
  name: "Aft\xEBsi lidhjeje"
Contact:
  name: Kontakt
DNS & Hosts:
  name: "DNS & Streh\xEB"
Development:
  name: Zhvillim
Draw:
  name: Vizatim
Ebook Reader:
  name: Lexues Elibrash
Email:
  name: Email
File Encryption & Vault:
  name: "Fsheht\xEBzim & Kasafort\xEB Kartelash"
File Transfer:
  name: "Shp\xEBrngulje Kartelash"
Finance Manager:
  name: "P\xEBrgjegj\xEBs Financash"
Firewall:
  name: Firewall
Forum:
  name: Forum
Gallery:
  name: Galeri
Graphics:
  name: Grafika
Habit Tracker:
  name: "Ndjek\xEBs Zakonesh"
Icon Pack:
  name: "Paket\xEB Ikonash"
Internet:
  name: Internet
Inventory:
  name: Inventar
Keyboard & IME:
  name: "Tastier\xEB & IME"
Launcher:
  name: "Nis\xEBs"
Local Media Player:
  name: "Lojt\xEBs Mediash Vendore"
Location Tracker & Sharer:
  name: "Gjurmues & Dh\xEBn\xEBs Vendndodhjesh"
Messaging:
  name: "Shk\xEBmbim Mesazhesh"
Multimedia:
  name: Multimedia
Music Practice Tool:
  name: Mjet Praktimi Muzike
Navigation:
  name: "L\xEBvizje"
Network Analyzer:
  name: Analizues Rrjeti
News:
  name: Lajme
Note:
  name: "Sh\xEBnim"
Online Media Player:
  name: "Lojt\xEBs Mediash N\xEB Internet"
Pass Wallet:
  name: "Kulet\xEB Fjal\xEBkalimesh"
Password & 2FA:
  name: "Fjal\xEBkalime & 2FA"
Phone & SMS:
  name: Telefon & SMS
Podcast:
  name: Podkast
Public Transport:
  name: Transport Publik
Radio:
  name: Radio
Reading:
  name: Lexim
Recipe Manager:
  name: "P\xEBrgjegj\xEBs Recetash Gatimi"
Religion:
  name: Fe
Science & Education:
  name: "Shkenc\xEB & Arsim"
Security:
  name: Siguri
Shopping List:
  name: "List\xEB Blerjesh"
Social Network:
  name: "Rrjet Shoq\xEBror"
Sports & Health:
  name: "Sporte & Sh\xEBndet"
System:
  name: Sistem
Task:
  name: "Pun\xEB"
Text Editor:
  name: "P\xEBrpunues Tekstesh"
Theming:
  name: Ndryshim teme grafike
Translation & Dictionary:
  name: "P\xEBrkthim & Fjalor"
Unit Convertor:
  name: "Shnd\xEBrrues Nj\xEBsish"
VPN & Proxy:
  name: "VPN & Nd\xEBrmjet\xEBs"
Voice & Video Chat:
  name: "Fjalosje Me Z\xEB & Video"
Wallet:
  name: "Kulet\xEB"
Wallpaper:
  name: Sfond
Weather:
  name: Mot
Workout:
  name: "St\xEBrvitje"
Writing:
  name: Shkrim
