archive:
  description: "Arkivi i depos zyrtare Software i Lir\xEB F-Droid. Aplikacionet k\xEB\
    tu jan\xEB t\xEB vjet\xEBr dhe mund t\xEB p\xEBrmbajn\xEB probleme t\xEB ditura\
    \ cenueshm\xEBrie dhe sigurie!"
  name: Arkiv F-Droid
repo:
  description: "Depoja zyrtare Software i Lir\xEB F-Droid. Gjith\xE7ka n\xEB k\xEB\
    t\xEB depo montohet p\xEBrher\xEB q\xEB nga kodi burim."
  name: F-Droid
