AI Chat:
  description: Assistentes de IA, chatbots e interfaces de modelo de linguagem grande
    (LLM)
  name: Conversar com IA
Action Game:
  description: "Jogos de a\xE7\xE3o, esporte, corrida e plataformas"
  name: "Jogo de a\xE7\xE3o"
Alarm Clock:
  description: "Defina o hor\xE1rio do alarme"
  name: "Rel\xF3gio/Alarme"
App Manager:
  description: "Gerencie, organize e controle aplicativos instalados, inten\xE7\xF5\
    es e permiss\xF5es"
  name: Gerenciador de aplicativos
App Store & Updater:
  description: "Descubra, instale e atualize aplicativos de reposit\xF3rios de software"
  name: Loja de apps e atualizador
Battery:
  description: "Monitore e otimize a vida \xFAtil da bateria, o uso de energia e o\
    \ carregamento"
  name: Bateria
Board Game:
  description: Jogo de tabuleiro, xadrez, go, jogo da velha
  name: Jogo de tabuleiro
Bookmark:
  description: Salve, organize e gerencie links favoritos e listas de leitura
  name: Marcador
Browser:
  description: Navegadores da Web para navegar na Internet e visualizar sites
  name: Navegador
Calculator:
  description: "Ferramentas de c\xE1lculo aritm\xE9tico, cient\xEDfico e matem\xE1\
    tico"
  name: Calculadora
Calendar & Agenda:
  description: "Agende eventos, lembretes, compromissos e planejadores di\xE1rios"
  name: "Calend\xE1rio e agenda"
Camera:
  description: "C\xE2mera, visualizador de c\xE2mera IP e gravador de v\xEDdeo"
  name: "C\xE2mera"
Card Game:
  description: "Jogo de cartas, paci\xEAncia"
  name: Jogo de cartas
Cast:
  description: Transmitir, UPnP, DLNA, FCast, AirPlay, Miracast
  name: Transmitir
Casual Game:
  description: Jogo casual simples
  name: Jogo casual
Clock:
  description: Informe a hora atual
  name: "Rel\xF3gio"
Cloud Storage & File Sync:
  description: "Fa\xE7a backup, sincronize e acesse arquivos remotamente por meio\
    \ de servi\xE7os em nuvem"
  name: "Armazenamento na nuvem e sincroniza\xE7\xE3o de arquivos"
Code & Forge:
  description: "Git, hospedagem de c\xF3digo-fonte, forge"
  name: "C\xF3digo e Forja"
Connectivity:
  name: Conectividade
Contact:
  description: "Aplicativos de cat\xE1logo de endere\xE7os, agenda telef\xF4nica e\
    \ gerenciamento de pessoas"
  name: Contato
DNS & Hosts:
  description: "Configure resolvedores de DNS, bloqueio de an\xFAncios, arquivo de\
    \ hosts e roteamento de dom\xEDnio"
  name: "DNS e dom\xEDnios"
Development:
  description: "Codifica\xE7\xE3o, programa\xE7\xE3o, IDE, terminal e ferramentas\
    \ de desenvolvedor"
  name: Desenvolvimento
Dice:
  description: "Seletor aleat\xF3rio"
  name: Dados
Diet:
  description: "Nutri\xE7\xE3o, calorias, gerenciamento de alimentos e rastreador"
  name: Dieta
Download:
  description: Downloader, gerenciador de downloads, cliente torrent
  name: Download
Draw:
  description: "Aplicativos de desenho, pintura, ilustra\xE7\xE3o e tela de arte digital"
  name: Desenhar
Ebook Reader:
  description: "Leia e-books, EPUB, PDF e livros e publica\xE7\xF5es digitais"
  name: Leitor de e-book
Educational Game:
  description: Aprenda no jogo, perguntas
  name: Jogo educacional
Email:
  description: Clientes de email para enviar, receber e gerenciar mensagens de email
  name: E-mail
Emulator:
  description: Emulador rodando jogo e programa
  name: Emulador
File Encryption & Vault:
  description: Criptografe, bloqueie e oculte arquivos e pastas particulares
  name: Criptografia de arquivos e cofres
File Manager:
  description: Gerenciador e explorador de arquivos
  name: Gerenciador de arquivos
File Transfer:
  description: Compartilhe e transfira arquivos via FTP, LAN, Bluetooth ou ponto a
    ponto (p2p)
  name: "Transfer\xEAncia de arquivos"
Finance Manager:
  description: "Acompanhe despesas, or\xE7amentos, receitas e contas financeiras pessoais"
  name: "Gerenciador de finan\xE7as"
Firewall:
  description: "Bloqueie o tr\xE1fego de rede indesejado e controle o acesso do aplicativo\
    \ \xE0 Internet"
  name: Firewall
Flashlight:
  description: Aplicativos de lanterna e flash LED
  name: Lanterna
Forum:
  description: "F\xF3runs de discuss\xE3o, t\xF3picos da comunidade e plataformas\
    \ de perguntas e respostas"
  name: "F\xF3rum"
Gallery:
  description: "Navegue, visualize e organize fotos, imagens e v\xEDdeos"
  name: Galeria
Game Helper:
  description: "Ajudante de jogo, assistente, companheiro, placar, cron\xF4metro"
  name: Ajudante de jogo
Graphics:
  description: "Ferramentas de edi\xE7\xE3o de imagens, manipula\xE7\xE3o de fotos\
    \ e design visual"
  name: "Gr\xE1ficos"
Habit Tracker:
  description: "Crie rotinas, monitore metas di\xE1rias e monitore sequ\xEAncias pessoais"
  name: "Rastreador de h\xE1bitos"
Health Manager:
  description: "Gerenciamento de peso, frequ\xEAncia card\xEDaca, press\xE3o arterial,\
    \ menstrua\xE7\xE3o e outras m\xE9tricas de sa\xFAde"
  name: "Gerenciamento de sa\xFAde"
Icon Pack:
  description: "Conjuntos de \xEDcones personalizados para \xEDcones de aplicativos\
    \ de estilo e tema"
  name: "Pacote de \xEDcones"
Internet:
  name: Internet
Inventory:
  description: "Rastreie, catalogue e gerencie itens f\xEDsicos e estoque"
  name: "Invent\xE1rio"
Keyboard & IME:
  description: "Teclados personalizados, m\xE9todos de entrada, corre\xE7\xE3o autom\xE1\
    tica e aplicativos de digita\xE7\xE3o"
  name: "Teclado e m\xE9todos de entrada"
Launcher:
  description: "Substitui\xE7\xF5es de tela inicial e aplicativos de ambiente de desktop"
  name: Tela inicial
Local Media Player:
  description: "Reproduza arquivos de \xE1udio e v\xEDdeo off-line armazenados no\
    \ seu dispositivo"
  name: "Reprodutor de m\xEDdia local"
Location Tracker & Sharer:
  description: "Compartilhe e monitore a localiza\xE7\xE3o GPS em tempo real com outras\
    \ pessoas"
  name: "Rastreador e compartilhador de localiza\xE7\xE3o"
Lyrics:
  description: Veja e pesquise por letras
  name: Letras
Market & Price:
  description: "Pre\xE7o, taxa de c\xE2mbio, estoque"
  name: "Mercado & Pre\xE7o"
Meditation:
  description: "Medita\xE7\xE3o, mente, respira\xE7\xE3o"
  name: "Medita\xE7\xE3o"
Messaging:
  description: "Aplicativos de mensagens instant\xE2neas, bate-papo e comunica\xE7\
    \xE3o por SMS"
  name: Mensageiros
Multimedia:
  name: "Multim\xEDdia"
Music Practice Tool:
  description: "Afinadores, metr\xF4nomos, ferramentas de acordes e aux\xEDlios para\
    \ pr\xE1tica de instrumentos"
  name: "Ferramenta de pr\xE1tica musical"
Navigation:
  description: "Mapas, GPS, instru\xE7\xF5es passo a passo e aplicativos de planejamento\
    \ de rotas"
  name: "Navega\xE7\xE3o"
Network Analyzer:
  description: "Diagnosticar Wi-Fi, verificar redes e monitorar o desempenho da conex\xE3\
    o"
  name: Analisador de rede
News:
  description: "\xDAltimas manchetes, artigos, feeds RSS e agregadores de not\xED\
    cias"
  name: "Not\xEDcias"
Note:
  description: "Blocos de notas, memorandos e aplicativos r\xE1pidos de anota\xE7\xF5\
    es e organiza\xE7\xE3o"
  name: Nota
Notification:
  description: "Gerenciador de notifica\xE7\xF5es, registrador, redirecionador, otimizador"
  name: "Notifica\xE7\xE3o"
OCR:
  description: "Scanner de documentos, reconhecimento \xF3ptico de caracteres"
  name: OCR
Online Media Player:
  description: "Transmita m\xFAsicas, v\xEDdeos e conte\xFAdo ao vivo da Internet"
  name: "Reprodutor de m\xEDdia on-line"
Party Game:
  description: Jogo de festa multijogador
  name: Jogo de festa
Pass Wallet:
  description: "Armazene cart\xF5es de embarque, ingressos, cart\xF5es de fidelidade\
    \ e cupons"
  name: Carteira de passe
Password & 2FA:
  description: "Gerenciadores de senhas, autenticadores, OTP, TOTP, HOTP, U2F, FIDO\
    \ e ferramentas de seguran\xE7a de dois fatores"
  name: Senhas e dois fatores
Phone & SMS:
  description: "Discadores, gerenciadores de chamadas e utilit\xE1rios de mensagens\
    \ de texto"
  name: Telefone & SMS
Platformer Game:
  description: Jogo de plataforma, rolagem lateral
  name: Jogo de plataforma
Podcast:
  description: "Assine, transmita e baixe epis\xF3dios e programas de \xE1udio de\
    \ podcast"
  name: Podcast
Public Transport:
  description: "Hor\xE1rios e planejadores de viagens de \xF4nibus, trem, metr\xF4\
    \ e transporte p\xFAblico"
  name: "Mapa de transporte p\xFAblico e hor\xE1rios"
Push:
  description: Mensagens push
  name: Push
Puzzle Game:
  description: "Quebra-cabe\xE7a, sudoku, jogo da mem\xF3ria"
  name: "Jogo de quebra-cabe\xE7a"
Radio:
  description: "Transmita esta\xE7\xF5es de r\xE1dio FM/AM ao vivo e transmiss\xF5\
    es de r\xE1dio pela Internet"
  name: "R\xE1dio"
Reading:
  description: "Artigos, conte\xFAdo extenso, leia mais tarde e aplicativos de leitura\
    \ da web"
  name: Leitura
Recipe Manager:
  description: "Armazene, organize e descubra receitas culin\xE1rias e ideias para\
    \ refei\xE7\xF5es"
  name: Gerenciador de receitas
Recorder:
  description: "Gravador de \xE1udio, tela, e liga\xE7\xE3o"
  name: Gravador
Religion:
  description: "Tempos de ora\xE7\xE3o, textos sagrados, devocionais e aplicativos\
    \ de pr\xE1tica espiritual"
  name: "Religi\xE3o"
Remote Access:
  description: Controle desktops, servidores e dispositivos remotamente via RDP, VNC
    ou SSH
  name: Acesso remoto
Remote Controller:
  description: "Controles remotos infravermelhos e dom\xE9sticos inteligentes para\
    \ TVs, unidades de CA e outros dispositivos"
  name: Controle remoto
Role-Playing Game:
  description: RPG, estilo rogue
  name: Jogo de RPG
Schedule:
  description: "Programa\xE7\xE3o para confer\xEAncia e evento"
  name: Agenda
Science & Education:
  description: "Aplicativos de aprendizagem, estudo, refer\xEAncia e educacionais"
  name: "Ci\xEAncia & Educa\xE7\xE3o"
Security:
  name: "Seguran\xE7a"
Shooter Game:
  description: Tiro ao alvo
  name: Jogo de tiro
Shopping List:
  description: Listas de compras, rastreadores de compras e aplicativos de compras
    colaborativas
  name: Lista de compra
Social Network:
  description: "M\xEDdia social, microblogging e plataformas de comunidades online"
  name: Redes sociais
Sport Game:
  description: Jogos esportivos
  name: Jogo de esporte
Sports & Health:
  description: "Acompanhamento de condicionamento f\xEDsico, bem-estar, resultados\
    \ esportivos e monitoramento de sa\xFAde"
  name: "Esportes & Sa\xFAde"
Stopwatch:
  description: "Medi\xE7\xE3o do progresso, cron\xF4metro de tempo decorrido e voltas"
  name: "Cron\xF4metro"
Strategy Game:
  description: "Estrat\xE9gia, simula\xE7\xE3o"
  name: "Jogo de estrat\xE9gia"
System:
  name: Sistema
Task:
  description: Listas de tarefas, gerenciadores de tarefas e ferramentas de produtividade
    e GTD
  name: Tarefa
Text Editor:
  description: Editores de texto simples, editores Markdown e ferramentas de escrita
  name: Editor de texto
Text to Speech:
  description: Ferramentas TTS
  name: Texto para fala
Theming:
  description: "Personalize a apar\xEAncia do seu dispositivo com temas, fontes e\
    \ estilos de UI"
  name: Temas
Time Tracker:
  description: Acompanhe o uso do tempo em atividades e tempo de tela
  name: Rastreador de tempo
Timer:
  description: Intervalos, contagem de tempo
  name: "Cron\xF4metro"
Translation & Dictionary:
  description: "Traduza idiomas, procure palavras e acesse refer\xEAncias de vocabul\xE1\
    rio"
  name: "Tradu\xE7\xE3o e dicion\xE1rio"
Unit Convertor:
  description: Converta entre unidades de comprimento, peso, temperatura, moeda e
    muito mais
  name: Conversor de unidades
VPN & Proxy:
  description: "Criptografe o tr\xE1fego, contorne restri\xE7\xF5es (contorno) e torne\
    \ sua conex\xE3o an\xF4nima"
  name: VPN e proxy
Visual Novel:
  description: "Novela visual, galgame, jogo de hist\xF3ria"
  name: Romance visual
Voice & Video Chat:
  description: "Aplicativos de chamadas de \xE1udio e v\xEDdeo, confer\xEAncias e\
    \ comunica\xE7\xE3o VoIP"
  name: "Liga\xE7\xE3o de voz e v\xEDdeo"
Volume:
  description: "Gerenciar configura\xE7\xE3o de volume"
  name: Volume
Wallet:
  description: "Carteiras digitais para pagamentos, cart\xF5es e gerenciamento de\
    \ criptomoedas"
  name: Carteira
Wallpaper:
  description: Tela inicial e plano de fundo da tela de bloqueio e aplicativos de
    papel de parede ao vivo
  name: Plano de fundo
Weather:
  description: "Aplicativos de previs\xF5es, radar, temperatura e condi\xE7\xF5es\
    \ atmosf\xE9ricas"
  name: Clima
Word Game:
  description: "Jogo de quebra-cabe\xE7a de palavras, palavras cruzadas, adivinha\xE7\
    \xE3o de palavras"
  name: Jogo de palavras
Workout:
  description: "Rotinas de exerc\xEDcios, aplicativos de monitoramento de academia,\
    \ corrida e treinamento f\xEDsico"
  name: "Exerc\xEDcio f\xEDsico"
Writing:
  description: "Processadores de texto, di\xE1rios, rascunhos e aplicativos de escrita\
    \ de formato longo"
  name: Escrita
