archive:
  description: "O arquivo do reposit\xF3rio oficial de software livre do F-Droid.\
    \ Os aplicativos aqui s\xE3o antigos e podem conter vulnerabilidades conhecidas\
    \ e problemas de seguran\xE7a!"
  name: Arquivo F-Droid
repo:
  description: "O reposit\xF3rio oficial de software livre do F-Droid. Tudo neste\
    \ reposit\xF3rio \xE9 compilado do c\xF3digo-fonte."
  name: F-Droid
