Ads:
  description: "Ta aplikacija vsebuje ogla\u0161evanje"
  name: Oglasi
DisabledAlgorithm:
  description: "Ta aplikacija ima \u0161ibek varnostni podpis"
  name: "Podpisano z neza\u0161\u010Ditenim algoritmom"
KnownVuln:
  description: Ta aplikacija vsebuje znano varnostno pomanjkljivost
  name: Znana ranljivost
NoSourceSince:
  description: "Izvorna koda ni ve\u010D na voljo, posodobitve niso mogo\u010De"
  name: "Izvorna koda ni ve\u010D dostopna od"
NonFreeAdd:
  description: "Ta aplikacija promovira pla\u010Dljive dodatke"
  name: Ne-prosti dodatki
NonFreeAssets:
  description: Ta aplikacija vsebuje neodprte enote
  name: Ne-prosta sredstva
NonFreeDep:
  description: Ta aplikcija je odvisna od ostalih ne odprtih aplikacijah
  name: Ne-proste odvisnosti
NonFreeNet:
  description: "Ta aplikacija promovira pla\u010Dljive internetne storitve"
  name: "Ne-prosti omre\u017Ene storitve"
TetheredNet:
  description: "To orodje je v celoti odvisno od dolo\u010Denega primera omre\u017E\
    ne storitve"
  name: "Vezano na zunanje omre\u017Ene storitve"
Tracking:
  description: "Ta aplikacija vam sledi in poro\u010Da o va\u0161i aktivnosti"
  name: Sledenje
