AI Chat:
  description: "Teko\xE4lyavustajat, chattibotit ja suurten kielimallien (LLM) k\xE4\
    ytt\xF6liittym\xE4t"
  name: Ai keskustelu
Action Game:
  description: Toiminta-, urheilu-, kilpa-ajo- ja tasohyppelypelit
  name: Toimintapeli
App Manager:
  description: "Hallitse, j\xE4rjest\xE4 ja valvo asennettuja sovelluksia, tavoitteita\
    \ ja k\xE4ytt\xF6oikeuksia"
  name: Sovellusten hallinta
App Store & Updater:
  description: "Etsi, asenna ja p\xE4ivit\xE4 sovelluksia ohjelmistovarastoista"
  name: "Sovelluskauppa & p\xE4ivitysohjelma"
Battery:
  description: "Seuraa ja optimoi akun k\xE4ytt\xF6ik\xE4\xE4, virrankulutusta ja\
    \ latausta"
  name: Akku
Board Game:
  description: Lautapeli, shakki, go, ristinolla
  name: Lautapeli
Bookmark:
  description: "Tallenna, j\xE4rjest\xE4 ja hallinnoi suosikkilinkkej\xE4 ja lukulistoja"
  name: Kirjanmerkki
Browser:
  description: Verkkoselaimet internetin selaamiseen ja verkkosivustojen katseluun
  name: Selain
Calculator:
  description: "Aritmeettiset, tieteelliset ja matemaattiset laskuty\xF6kalut"
  name: Laskin
Calendar & Agenda:
  description: "Aikatauluta tapahtumia, muistutuksia, tapaamisia ja p\xE4ivitt\xE4\
    isi\xE4 suunnittelijoita"
  name: Kalenteri & esityslista
Camera:
  description: Kamera, IP-kamerakatselulaite ja videonauhuri
  name: Kamera
Card Game:
  description: Korttipeli, pasianssi
  name: Korttipeli
Casual Game:
  description: Yksinkertainen rento peli
  name: Rento peli
Clock:
  description: "H\xE4lytys-, sekuntikello- ja maailmankelloapuohjelmat"
  name: Kello
Cloud Storage & File Sync:
  description: "Varmuuskopioi, synkronoi ja k\xE4yt\xE4 tiedostoja et\xE4n\xE4 pilvipalveluiden\
    \ kautta"
  name: Pilvitallennus ja tiedostojen synkronointi
Connectivity:
  name: Yhteydet
Contact:
  description: "Osoitekirja, puhelinluettelo ja henkil\xF6st\xF6nhallintasovellukset"
  name: "Ota yhteytt\xE4"
DNS & Hosts:
  description: "M\xE4\xE4rit\xE4 DNS-resolverit, mainosten esto, is\xE4nt\xE4tiedosto\
    \ ja verkkotunnuksen reititys"
  name: "DNS ja is\xE4nn\xE4t"
Development:
  description: "Koodaus, ohjelmointi, IDE, p\xE4\xE4te ja kehitt\xE4j\xE4ty\xF6kalut"
  name: "Kehitt\xE4minen"
Dice:
  description: Satunnainen valitsin
  name: Noppa
Diet:
  description: Ravitsemus, kalorit, ruoan hallinta ja seuranta
  name: Ruokavalio
Download:
  description: Lataaja, latausten hallintaohjelma ja torrent-asiakasohjelma
  name: Lataa
Draw:
  description: Luonnostelu-, maalaus-, kuvitus- ja digitaalisen taiteen piirtoalussovellukset
  name: "Piirt\xE4minen"
Ebook Reader:
  description: Lue e-kirjoja, EPUB, PDF ja digitaalisia kirjoja ja julkaisuja
  name: E-kirjan lukija
Educational Game:
  description: "Opi peliss\xE4, tietokilpailu"
  name: Opettavainen peli
Email:
  description: "S\xE4hk\xF6postiohjelmat s\xE4hk\xF6postiviestien l\xE4hett\xE4miseen,\
    \ vastaanottamiseen ja hallintaan"
  name: "S\xE4hk\xF6posti"
Emulator:
  description: "Emulaattori on p\xE4\xE4ll\xE4"
  name: Emulaattori
File Encryption & Vault:
  description: "Salata, lukita ja piilottaa yksityisi\xE4 tiedostoja ja kansioita"
  name: Tiedoston salaus & holvi
File Manager:
  description: Tiedostonhallinta ja tutkiminen
  name: Tiedostonhallinta
File Transfer:
  description: "Jaa ja siirr\xE4 tiedostoja FTP:n, LAN:n, Bluetoothin tai vertaisverkkoon\
    \ (p2p)"
  name: Tiedostonsiirto
Finance Manager:
  description: "Kustannukset, budjetit, tulot ja henkil\xF6kohtaiset tilit"
  name: "Talousp\xE4\xE4llikk\xF6"
Firewall:
  description: "Est\xE4 ei-toivottu verkkoliikenne ja hallitse sovellusten internet-yhteytt\xE4"
  name: Palomuuri
Flashlight:
  description: Led Flash Light -sovellukset
  name: Taskulamppu
Forum:
  description: "Keskustelulautakunnat, yhteis\xF6kierrokset ja Q&A-alustat"
  name: Foorumi
Gallery:
  description: "Selaa, katsele ja j\xE4rjest\xE4 kuvia, kuvia ja videoita"
  name: Galleria
Game Helper:
  description: Pelin apulainen, avustaja, seuralainen, tulostaulu, ajastin
  name: Pelin avustaja
Graphics:
  description: "Kuvank\xE4sittely, valokuvan manipulointi ja visuaalinen suunnitteluty\xF6\
    kalut"
  name: Grafiikka
Habit Tracker:
  description: "Rakenna rutiineja, seuraa p\xE4ivitt\xE4isi\xE4 tavoitteita ja seuraa\
    \ henkil\xF6kohtaisia rajoja"
  name: Rutiinien seuranta
Health Manager:
  description: Johtava paino, syke, verenpaine, kuukautiset ja muut terveysmittarit
  name: "Terveysl\xE4\xE4k\xE4ri"
Icon Pack:
  description: Custom-kuvakesarjat tyyliin ja teema-sovelluksen kuvakkeet
  name: Kuvakepaketti
Internet:
  name: Internet
Inventory:
  description: "Seuraa, luetteloi ja hallitse fyysisi\xE4 esineit\xE4 ja varastoa"
  name: Varasto
Keyboard & IME:
  description: "Mukautetut n\xE4pp\xE4imist\xF6t, sy\xF6tt\xF6menetelm\xE4t, autokorrektit\
    \ ja kirjoitussovellukset"
  name: "N\xE4pp\xE4imist\xF6 ja tekstinsy\xF6tt\xF6"
Launcher:
  description: "Kotin\xE4yt\xF6n korvaaminen ja ty\xF6p\xF6yt\xE4ymp\xE4rist\xF6sovellukset"
  name: "K\xE4ynnistin"
Local Media Player:
  description: "Pelaa offline-\xE4\xE4ni- ja videotiedostoja, jotka on tallennettu\
    \ laitteellesi"
  name: Paikallisen median soitin
Location Tracker & Sharer:
  description: Jaa ja seuraa reaaliaikaista GPS-sijaintia muiden kanssa
  name: Sijainnin seuranta ja jakaminen
Lyrics:
  description: Katso ja etsi lyriikoita
  name: Lyriikat
Market & Price:
  description: Hinta, valuuttakurssi, osake
  name: Markkinat ja hinta
Meditation:
  description: "Meditaatio, mindfulness, hengitysk\xE4yt\xE4nt\xF6"
  name: Meditaatio
Messaging:
  description: Pikaviesti-, chat- ja tekstiviestisovellukset
  name: Viestit
Multimedia:
  name: Media
Music Practice Tool:
  description: "Tuners, metronomeja, sointuty\xF6kaluja ja instrumenttien k\xE4yt\xE4\
    nn\xF6n apua"
  name: Soitonharjoittelu
Navigation:
  description: "Kartat, GPS, k\xE4\xE4nnettyj\xE4 ohjeita ja reittisuunnittelusovelluksia"
  name: Navigointi
Network Analyzer:
  description: "Diagnoosi Wi-Fi, skannausverkot ja seurantayhteyden suorituskyky\xE4"
  name: Verkkoanalysaattori
News:
  description: "Viimeisimm\xE4t otsikot, artikkelit, RSS-sy\xF6tteet ja uutisaggregaattorit"
  name: Uutiset
Note:
  description: Tietoja, muistioita ja nopea muistiinpanojen ja organisaation sovelluksia
  name: Muistiinpano
Online Media Player:
  description: "Musiikkia, videoita ja live-sis\xE4lt\xF6\xE4 internetist\xE4"
  name: Verkkomediasoitin
Party Game:
  description: Moninpeli, Party Game
  name: Puolueen peli
Pass Wallet:
  description: "S\xE4ilyt\xE4 lippuja, etukortteja ja kuponkeja"
  name: Salasana lompakko
Password & 2FA:
  description: "Salasananhallintaohjelmat, todentajat, OTP, TOTP, HOTP, U2F, FIDO\
    \ ja kaksiosaiset tietoturvaty\xF6kalut"
  name: Salasana ja kaksivaiheinen todennus
Phone & SMS:
  description: Soittoohjelmat, puheluiden hallintaohjelmat ja tekstiviestien apuohjelmat
  name: Puhelin ja tekstiviestit
Platformer Game:
  description: "Tasohyppelypeli, sivulta vieritt\xE4v\xE4 peli"
  name: Tasohyppelypeli
Podcast:
  description: "Tilaa, suoratoista ja lataa podcast-\xE4\xE4nijaksoja ja -ohjelmia"
  name: Podcast
Public Transport:
  description: Bussi-, juna-, metro- ja joukkoliikenteen aikataulut ja matkasuunnittelijat
  name: Joukkoliikenne
Puzzle Game:
  description: Pulmapeli, sudoku, muistipeli
  name: Pulmapeli
Radio:
  description: "Suoratoista FM/AM-radioasemia ja internetradiol\xE4hetyksi\xE4 suorana"
  name: Radio
Reading:
  description: "Artikkelit, pitk\xE4kestoinen sis\xE4lt\xF6, lue my\xF6hemmin -toiminnot\
    \ ja verkkolukijasovellukset"
  name: Lukeminen
Recipe Manager:
  description: "Tallenna, j\xE4rjest\xE4 ja l\xF6yd\xE4 ruoanlaittoreseptej\xE4 ja\
    \ ateriaideoita"
  name: Reseptien hallinta
Recorder:
  description: "\xC4\xE4ni, kuva, puhelu tallenne"
  name: Tallenne
Religion:
  description: "Rukousajat, pyh\xE4t tekstit, hartauskirjat ja hengellisen harjoituksen\
    \ sovellukset"
  name: Uskonto
Remote Access:
  description: "Hallitse ty\xF6p\xF6yti\xE4, palvelimia ja laitteita et\xE4n\xE4 RDP:n,\
    \ VNC:n tai SSH:n kautta"
  name: "Et\xE4k\xE4ytt\xF6"
Remote Controller:
  description: "IR- ja \xE4lykotikaukos\xE4\xE4timet televisioille, ilmastointilaitteille\
    \ ja muille laitteille"
  name: Kauko-ohjaus
Role-Playing Game:
  description: RPP, rogue
  name: Roolipeli
Schedule:
  description: Konferenssin ja tapahtuman aikataulu
  name: Aikataulu
Science & Education:
  description: Oppimis-, opiskelu-, haku- ja koulutussovellukset
  name: Tiede ja koulutus
Security:
  name: Turvallisuus
Shooter Game:
  description: Ampumakohde
  name: Ampumapeli
Shopping List:
  description: "Ostoslistat, ostosten seuranta ja yhteisty\xF6sovellukset"
  name: Ostoslista
Social Network:
  description: "Sosiaalinen media, mikrobloggaus ja verkkoyhteis\xF6alustat"
  name: Sosiaalinen verkosto
Sport Game:
  description: Urheilupelit
  name: Urheilupeli
Sports & Health:
  description: Kuntoilun seuranta, hyvinvointi, urheilutulokset ja terveyden seuranta
  name: Urheilu ja terveys
Strategy Game:
  description: Strategia, simulaatio
  name: Strategia peli
System:
  name: "J\xE4rjestelm\xE4"
Task:
  description: "Teht\xE4v\xE4listat, teht\xE4vienhallinta sek\xE4 tuottavuus- ja GTD-ty\xF6\
    kalut"
  name: "Teht\xE4v\xE4"
Text Editor:
  description: "Pelk\xE4t tekstieditorit, Markdown-editorit ja kirjoitusty\xF6kalut"
  name: Tekstimuokkain
Text to Speech:
  description: "TTS ty\xF6kalut"
  name: "Tekstist\xE4 puheeksi"
Theming:
  description: "Mukauta laitteesi ulkoasua teemoilla, fonteilla ja k\xE4ytt\xF6liittym\xE4\
    tyyleill\xE4"
  name: teemoinnista
Time Tracker:
  description: "Seuraa aktiviteettien ja n\xE4yt\xF6n ajastimen k\xE4ytt\xF6\xE4"
  name: Ajan seuranta
Timer:
  description: "Intervalliajoitus, ajanotto, l\xE4ht\xF6laskenta"
  name: Ajastin
Translation & Dictionary:
  description: "K\xE4\xE4nn\xE4 kieli\xE4, hae sanoja ja k\xE4yt\xE4 sanastoviitteit\xE4"
  name: "K\xE4\xE4nn\xF6s ja sanakirja"
Unit Convertor:
  description: "Muunna pituus-, paino-, l\xE4mp\xF6tila-, valuutta- ja muiden yksik\xF6\
    iden v\xE4lill\xE4"
  name: "Yksikk\xF6muunnin"
VPN & Proxy:
  description: "Salaa liikenne, ohita rajoitukset (kiert\xE4minen) ja anonymisoi yhteytesi"
  name: "VPN ja v\xE4lityspalvelin"
Visual Novel:
  description: Visuaalinen novelli, treffipeli, tarinapeli
  name: Visuaalinen novelli
Voice & Video Chat:
  description: "\xC4\xE4ni- ja videopuhelu-, neuvottelu- ja VoIP-viestint\xE4sovellukset"
  name: "\xC4\xE4ni- ja videokeskustelu"
Wallet:
  description: Digitaaliset lompakot maksuille, korteille ja kryptovaluuttojen hallinnalle
  name: Lompakko
Wallpaper:
  description: "Aloitusn\xE4yt\xF6n ja lukitusn\xE4yt\xF6n taustakuvat ja live-taustakuvat"
  name: Taustakuva
Weather:
  description: "Ennusteet, tutka-, l\xE4mp\xF6tila- ja ilmakeh\xE4n olosuhteet -sovellukset"
  name: "S\xE4\xE4"
Word Game:
  description: "Sanapeli, ristisanateht\xE4v\xE4, sanan arvaus"
  name: Sanapeli
Workout:
  description: Liikuntaohjelmat, kuntosalin seuranta, juoksu ja kuntoharjoittelusovellukset
  name: Kuntoilu
Writing:
  description: "Tekstink\xE4sittely-, p\xE4iv\xE4kirja-, luonnostelu- ja pitk\xE4\
    n tekstin kirjoitussovellukset"
  name: Kirjoittaminen
