Connectivity:
  name: Azday
Development:
  name: "asbu\u0263lu"
Graphics:
  name: "Tiwwun\u0263a"
Internet:
  name: antirnit
Reading:
  name: "ti\u0263uri"
Science & Education:
  name: Tamassant d usegmi
System:
  name: Anegraw
Writing:
  name: Tirra
