Ads:
  description: Denne app indeholder reklamer
  name: Reklamer
DisabledAlgorithm:
  description: Denne app har en svag sikkerhedssignatur
  name: Signeret med en usikker algoritme
KnownVuln:
  description: "Denne app indeholder en kendt s\xE5rbarhed"
  name: "Kendt s\xE5rbarhed"
NoSourceSince:
  description: "Denne kilde er ikke l\xE6ngere tilg\xE6ngelig, ingen opdateringer\
    \ mulig"
  name: Ingen kilde siden
NonFreeAdd:
  description: "Denne app fremmer ikke-frie tilf\xF8jelser"
  name: "Ikke frie tilf\xF8jelser"
NonFreeAssets:
  description: Denne app indeholder ikke-frit indhold
  name: Ikke frie genstande
NonFreeDep:
  description: "Denne app er afh\xE6ngig af andre ikke-frie apps"
  name: "Ikke frie afh\xE6ngigheder"
NonFreeNet:
  description: "Appen fremmer ikke-frie netv\xE6rkstjenester"
  name: "Ikke-frie netv\xE6rkstjenester"
TetheredNet:
  description: "Denne app afh\xE6nger helt af en bestemt instans af en netv\xE6rkstjeneste"
  name: "Bundne Netv\xE6rkstjenester"
Tracking:
  description: Denne app sporer og indberetter din aktivitet
  name: Sporing
