Ads:
  description: "Tiu \u0109i aplika\u0135o enhavas reklamojn"
  name: Reklamoj
DisabledAlgorithm:
  description: "Tiu \u0109i aplika\u0135o posedas malfortan sekurecan subskribon"
  name: Subskribita per malsekura algoritmo
KnownVuln:
  description: "Tiu \u0109i aplika\u0135o posedas sekurecan vundeblon"
  name: Konata sekureca vundeblo
NoSourceSince:
  description: "La fontkodo ne estas plu disponebla, neniu ebla \u011Disdatigo"
  name: Nedisponebla fontkodo
NonFreeAdd:
  description: "Tiu \u0109i aplika\u0135o favoras neliberajn aldona\u0135ojn"
  name: "Neliberaj aldona\u0135oj"
NonFreeAssets:
  description: "Tiu \u0109i aplika\u0135o enhavas neliberan enhavon"
  name: Nelibera enhavo
NonFreeDep:
  description: "Tiu \u0109i aplika\u0135o dependas de aliaj neliberaj aplika\u0135\
    oj"
  name: Neliberaj dependecoj
NonFreeNet:
  description: "Tiu \u0109i aplika\u0135o favoras a\u016D tute dependas de nelibera\
    \ retservo"
  name: Neliberaj retservoj
TetheredNet:
  description: "Tiu \u0109i aplika\u0135o tute dependas de difinita ekzemplo de reta\
    \ servo"
  name: Alligita al retservo
Tracking:
  description: "Tiu \u0109i aplika\u0135o spuras kaj raportas vian agadon"
  name: Spurado
