AI Chat:
  description: Asistiloj de artefarita intelekto, retbabilejaj robotoj kaj fasadoj
    por grandaj lingv-modeloj
  name: Artefarita intelekto
Action Game:
  description: Rapidagaj, sportaj, kurkonkursaj kaj platformaj bitludoj
  name: Rapidagaj ludoj
Alarm Clock:
  description: Agordi alarmon je difinita tempo
  name: "Vekhorlo\u011Doj"
App Manager:
  description: "Administri, organizi kaj regi instalitajn aplika\u0135ojn, ekigilojn\
    \ \xABIntent\xBB, permesojn"
  name: "Administriloj de aplika\u0135oj"
App Store & Updater:
  description: "Malkovri, instali kaj \u011Disdatigi aplika\u0135ojn el deponejoj\
    \ de aplika\u0135oj"
  name: "Deponejoj kaj \u011Disdatigiloj de aplika\u0135oj"
Battery:
  description: "Kontroli kaj plejbonigi vivecon de baterio, konsumon de energio kaj\
    \ \u015Dargadon"
  name: Baterio
Board Game:
  description: "Tabulludoj, \u015Dakludo, goo, Krucoj-kaj-nuloj"
  name: Tabulludoj
Bookmark:
  description: Konservi, organizi kaj administri ligilojn kaj leglistojn
  name: Administriloj de legosignoj
Browser:
  description: Retfoliumiloj (retumiloj) por krozi la interreton
  name: Retfoliumiloj
Calculator:
  description: Iloj por fari aritmetikajn, sciencajn kaj matematikajn kalkulojn
  name: Kalkuliloj
Calendar & Agenda:
  description: "Plani okaza\u0135ojn, farenda\u0135ojn, renkontojn kaj \u0109iutagajn\
    \ taskojn"
  name: Kalendaroj kaj tempplanoj
Camera:
  description: "Aplika\u0135oj de fotilo, rigardiloj de IP-fotilo kaj aplika\u0135\
    oj de kamerao"
  name: Fotilo
Card Game:
  description: Kartludoj, paciencludoj (ermitludoj)
  name: Kartludoj
Cast:
  description: Dissendado, UPnP, DLNA, FCast, AirPlay, Miracast
  name: Dissendado
Casual Game:
  description: "Facilaj bitludoj por \u0109iu tago"
  name: Okazaj ludoj
Clock:
  description: Vidigi nunan tempon
  name: "Horlo\u011Doj"
Cloud Storage & File Sync:
  description: Sekurkopii, samtempigi kaj telealiri dosierojn en nubaj servoj
  name: Nuba konservado kaj dosiera samtempigo
Code & Forge:
  description: Git, retgastigo de fontkodo, kunlabora programado
  name: Kodo kaj programado
Connectivity:
  name: Konekteco
Contact:
  description: Adresaroj kaj organiziloj de kontaktoj
  name: Listoj de kontaktoj
DNS & Hosts:
  description: "Agordi DNS-servilojn, reklam-blokilojn, dosieron \xABhosts\xBB kaj\
    \ enkursigon de nomregnoj"
  name: DNS kaj retgastigo
Development:
  description: "Terrminal-imitiloj, programadaj \u0109irka\u016Da\u0135oj kaj iloj\
    \ por programistoj"
  name: Programado
Dice:
  description: Generiloj de hazardo
  name: "\u0134etkuboj"
Diet:
  description: "Spuri kaj administri man\u011Da\u0135ojn, kaloriojn kaj nutradon"
  name: Dieto
Download:
  description: "Administriloj de el\u015Dutoj kaj BitTorent-klientoj"
  name: "El\u015Dutiloj"
Draw:
  description: "Iloj por desegni, pentri, krei ilustra\u0135ojn kaj por cifereca grafiko"
  name: Desegnado
Ebook Reader:
  description: Legi elektronikajn librojn, bildstriojn kaj dokumentojn; PDF, EPUB
  name: Legiloj de bitlibroj
Educational Game:
  description: Lerni per ludo, demandaroj
  name: Edukaj ludoj
Email:
  description: "Retpo\u015Dtilojn: sendi, ricevi kaj administri retpo\u015Dton"
  name: "Retpo\u015Dto"
Emulator:
  description: Imitiloj, kiuj ebligas ruli malnovajn ludojn kaj programojn
  name: Lud-imitiloj
File Encryption & Vault:
  description: "\u0108ifri, bloki kaj ka\u015Di privatajn dosier(uj)ojn"
  name: "Dosiera \u0109ifrado"
File Manager:
  description: Organizi kaj foliumi dosierojn
  name: Dosier-administriloj
File Transfer:
  description: "Kunhavigi kaj transigi dosierojn per FTP, loka reto, Bludento a\u016D\
    \ samtavolaj retoj (P2P)"
  name: Dosiera kunhavigo
Finance Manager:
  description: "Spuri elspezojn, bu\u011Detojn, enspezojn kaj kontojn"
  name: Financ-administriloj
Firewall:
  description: "Bloki nedeziratan retan trafikon kaj regi interretan aliron de aplika\u0135\
    oj"
  name: "Farjo\u015Dirmiloj"
Flashlight:
  description: "Utiligi LED-on a\u016D ekranon kiel po\u015Dlampon"
  name: "Po\u015Dlampo"
Forum:
  description: "Forumoj, diskut-fadenoj kaj platformoj \u201Cdemandoj kaj respondoj\u201D"
  name: Diskutejoj
Gallery:
  description: Foliumi, vidigi kaj organizi fotojn, bildojn kaj filmetojn
  name: Bild-foliumiloj
Game Helper:
  description: Asistiloj por ludoj, poenttabuloj, temp-mezuriloj
  name: Lud-helpiloj
Graphics:
  description: Redakti kaj pritrakti fotojn, grafikaj iloj
  name: Grafiko
Habit Tracker:
  description: Prilabori kutimojn, spuri tagajn celojn kaj personajn emojn
  name: Spuriloj de kutimoj
Health Manager:
  description: Spuri pezon, pulson, sangpremon, menstruan ciklon kaj aliajn sanajn
    statistikojn
  name: Administriloj de sano
Icon Pack:
  description: "Propraj aroj da bildsimboloj por unuecigi aspekton de piktogramoj\
    \ de aplika\u0135oj"
  name: "Bildsimbol-paka\u0135oj"
Internet:
  name: Interreto
Inventory:
  description: "Spuri, katalogi kaj administri posedatajn a\u0135ojn"
  name: "Administriloj de poseda\u0135oj"
Keyboard & IME:
  description: "Propraj klavaroj, enig-metodoj, skrib-korektiloj kaj tajpaj aplika\u0135\
    oj"
  name: Klavaroj
Launcher:
  description: "Neoficialaj aplika\u0135oj de \u0109efekrano (aplika\u0135lan\u0109\
    iloj) kaj fenestriloj"
  name: "Aplika\u0135lan\u0109iloj"
Local Media Player:
  description: "Ludi sonajn kaj filmajn dosierojn trovi\u011Dantajn en via aparato"
  name: "Ludiloj de lokaj a\u016Ddvida\u0135oj"
Location Tracker & Sharer:
  description: Kunhavigi kaj spuri geografian pozicion realtempe
  name: Spuriloj (kaj kunhavigiloj) de pozicio
Lyrics:
  description: Montri kaj trovi tekstojn de kantoj
  name: Kanttekstoj
Market & Price:
  description: Prezoj, valutoj, kurzoj
  name: Merkato kaj prezoj
Meditation:
  description: Plenatenta meditado, ekzercado de spiro
  name: Meditado
Messaging:
  description: "Tujmesa\u011Diloj, babilejaj kaj SMS-aj aplika\u0135oj"
  name: Komunikiloj
Multimedia:
  name: Sono kaj video
Music Practice Tool:
  description: Agordiloj, metronomoj, akordaj iloj kaj helpiloj por muzik-lernantoj
  name: Muzik-ekzerciloj
Navigation:
  description: "Mapoj, GPS, navigiloj kaj aplika\u0135oj por plani kursoj"
  name: Navigado
Network Analyzer:
  description: Kontroli vifion, skani retojn kaj spuri rendimenton de konekto
  name: Analiziloj de retkonektoj
News:
  description: "Nova\u0135oj, artikoloj, RSS-abonfluoj kaj nova\u0135-kolektiloj"
  name: "Legiloj de nova\u0135oj"
Note:
  description: "Notiloj, memorigiloj, kaj aplika\u0135oj por rapide fari kaj organizi\
    \ notojn"
  name: Notlibroj
Notification:
  description: Iloj por administri, registri, alidirekti kaj plivastigi sciigojn
  name: Sciigoj
OCR:
  description: Dokument-skaniloj, optika signorekono
  name: Optika signorekono
Online Media Player:
  description: Ludi elsendfluan muzikon/filmojn el la interreto
  name: "Ludiloj de foraj a\u016Ddvida\u0135oj"
Party Game:
  description: Plurpersonaj ludoj
  name: Plurpersonaj ludoj
Pass Wallet:
  description: Teni ferdek-kartojn, biletojn, lojalec-kartojn, kaj kuponojn
  name: Biletujoj (por lojalec-kartoj)
Password & 2FA:
  description: "Administriloj de pasvortoj, iloj por 2-pa\u015Da a\u016Dtentigo kaj\
    \ OTP, TOTP, HOTP, U2F kaj FIDO"
  name: "Pasvort-administriloj kaj dupa\u015Daj a\u016Dtentigiloj"
Phone & SMS:
  description: "Aplika\u0135oj por telefoni, administri telefonajn konektojn kaj tekstmesa\u011D\
    i"
  name: Telefonado kaj SMS
Platformer Game:
  description: Platformaj kaj flank-rulumaj bitludoj
  name: Platformaj ludoj
Podcast:
  description: "Aboni, a\u016Dskulti kaj el\u015Duti interretajn elsendojn (podkastojn)"
  name: Ludiloj de aboneblaj sondosieroj (podkastoj)
Public Transport:
  description: "A\u016Dtobusaj, tramaj kaj fervojaj horaroj, planiloj de voja\u011D\
    o"
  name: Publika transporto
Push:
  description: "Pu\u015D-sciigoj"
  name: "Pu\u015D-te\u0125nologio"
Puzzle Game:
  description: Logikaj kaj memor-ekzercaj bitludoj, sudoko
  name: Logikaj ludoj
Radio:
  description: "A\u016Dskulti radion: FM, AM kaj interretan"
  name: Radio
Reading:
  description: "Artikoloj, ampleksaj tekstoj, ret-legiloj, kaj aplika\u0135oj \u201C\
    legi poste\u201D (administriloj de legosignoj)"
  name: Legado
Recipe Manager:
  description: "Teni, organizi kaj malkovri kuir-receptojn kaj ideojn pri man\u011D\
    a\u0135oj"
  name: Administriloj de kuir-receptoj
Recorder:
  description: Registri sonon, surekranan aktivecon kaj telefonajn interparoladojn
  name: Registriloj
Religion:
  description: "Pre\u011D-horaroj, sanktaj tekstoj, pre\u011Doj kaj asistiloj de spirita\
    \ disvolvi\u011Do"
  name: Religio
Remote Access:
  description: "Teleregi komputilojn, servilojn kaj aparatojn per RDP, VNC a\u016D\
    \ SSH"
  name: Fora aliro
Remote Controller:
  description: "Teleregiloj transru\u011Daj, Bludentaj, ktp por televidiloj kaj domaj\
    \ elektronika\u0135oj"
  name: Teleregiloj
Role-Playing Game:
  description: "Rolaj (RPG) kaj labirint-esploradaj (\xABroguelike\xBB) bitludoj"
  name: Rolaj ludoj
Schedule:
  description: "Horplanoj de konferencoj kaj okaza\u0135oj"
  name: Horplanoj
Science & Education:
  description: "Aplika\u0135oj por lerni, parkerigi kaj studi"
  name: Scienco kaj edukado
Security:
  name: Sekureco
Shooter Game:
  description: Pafado al celoj
  name: Pafaj ludoj
Shopping List:
  description: "Listoj de a\u0109etoj kaj kunlabora a\u0109etado"
  name: "Listoj de a\u0109etoj"
Social Network:
  description: Sociaj komunikiloj, taglibretoj (mikroblogoj) kaj interretaj komunumaj
    platformoj
  name: Sociaj komunikiloj
Sport Game:
  description: Sportaj bitludoj
  name: Sportaj ludoj
Sports & Health:
  description: Spuri korpan/mensan sanon, korpan aktivecon kaj poentaron dum sportoj
  name: Sporto kaj sano
Stopwatch:
  description: Mezuri temppason, rondirojn
  name: "Temp-mezuriloj (klikhorlo\u011Doj)"
Strategy Game:
  description: Strategiaj kaj simuladaj bitludoj
  name: Strategiaj ludoj
System:
  name: Operaciumaj iloj
Task:
  description: "Listoj de farenda\u0135oj kaj taskoj, metodo \u201Cigi aferojn finitaj\u201D"
  name: Planiloj
Text Editor:
  description: Redaktiloj de plata teksto, Markdown kaj pli
  name: Tekst-redaktiloj
Text to Speech:
  description: "Konverti tekston al vo\u0109o"
  name: Parolsinteziloj
Theming:
  description: "Personecigi vian aparaton per ha\u016Dtoj, tiparoj kaj stiloj de fasado"
  name: "Ha\u016Dtoj (etosoj)"
Time Tracker:
  description: "Spuri tempon pasigitan je specifaj agoj kaj tempon \u0109e ekrano"
  name: Temp-mezuriloj
Timer:
  description: "Mezuri intertempojn, te\u0125niko Pomodoro, mezuri tempon malanta\u016D\
    en"
  name: Temp-mezuriloj (retrokalkulaj)
Translation & Dictionary:
  description: Traduki inter lingvoj, trovi signifojn de vortoj
  name: Tradukiloj kaj vortaroj
Unit Convertor:
  description: Konverti inter unuoj de longo, maso, temperaturo, valuto kaj pli
  name: Konvertiloj de unuoj
VPN & Proxy:
  description: "\u0108ifri datumtrafikon, preterpasi blokadojn kaj anonimigi vian\
    \ retkonekton"
  name: VPN kaj retperiloj
Visual Novel:
  description: "Vidaj romanoj, bish\u014Djo, interaga fikcio"
  name: Vidaj romanoj
Voice & Video Chat:
  description: "Aplika\u0135oj por (vid)telefonvokoj, telekunvenoj kaj VoIP"
  name: Sonaj/videaj komunikiloj
Volume:
  description: "Iloj por administri la\u016Dtecon"
  name: Sonforteco
Wallet:
  description: "Ciferecaj monujoj por pagi, kartoj kaj \u0109ifromonoj"
  name: Monujoj
Wallpaper:
  description: "Ekranfonoj por hejmekrano kaj \u015Dlosekrano kaj movbildaj ekranfonoj"
  name: Ekranfonoj
Weather:
  description: "Prognozoj, radaraj bildoj, temperaturo kaj veterkondi\u0109oj"
  name: Veterprognozo
Word Game:
  description: Krucvortenigmoj, diveni vortojn
  name: Vortaj ludoj
Workout:
  description: Plani ekzercojn, spuri progreson en ekzercejo, kurado kaj trejnado
  name: Trejnado
Writing:
  description: "Dokument-redaktiloj, aplika\u0135oj por konduki taglibron, malnetojn\
    \ a\u016D skribi pli longajn tekstojn"
  name: Skribado
