Ads:
  description: "Esta aplica\xE7\xE3o cont\xE9m publicidade"
  name: "An\xFAncios"
DisabledAlgorithm:
  description: "Esta aplica\xE7\xE3o tem uma assinatura de seguran\xE7a fraca"
  name: Assinado usando um algoritmo inseguro
KnownVuln:
  description: "Esta aplica\xE7\xE3o cont\xE9m uma falha de seguran\xE7a conhecida"
  name: Vulnerabilidade conhecida
NoSourceSince:
  description: "O c\xF3digo-fonte acabou de estar dispon\xEDvel, atualiza\xE7\xF5\
    es n\xE3o s\xE3o poss\xEDveis"
  name: Sem fonte desde
NonFreeAdd:
  description: "Esta aplica\xE7\xE3o promove add-ons n\xE3o livres"
  name: "Complementos n\xE3o livres"
NonFreeAssets:
  description: "Esta aplica\xE7\xE3o cont\xE9m conte\xFAdo n\xE3o livre"
  name: "Ativos n\xE3o livres"
NonFreeDep:
  description: "Esta aplica\xE7\xE3o depende de aplica\xE7\xF5es n\xE3o livres"
  name: "Depend\xEAncias n\xE3o livres"
NonFreeNet:
  description: "Esta app promove ou depende inteiramente de um servi\xE7o de rede\
    \ n\xE3o livre"
  name: "Servi\xE7os de rede n\xE3o livres"
TetheredNet:
  description: "Esta app depende inteiramente de uma determinada inst\xE2ncia de um\
    \ servi\xE7o de rede"
  name: "Servi\xE7os de rede com fios"
Tracking:
  description: "Esta aplica\xE7\xE3o monitoriza e reporta a sua atividade"
  name: Rastreamento
