Ads:
  description: "Esta aplicaci\xF3n contiene publicidad"
  name: Anuncios
NonFreeAdd:
  description: "Esta aplicaci\xF3n promueve complementos no gratuitos"
NonFreeAssets:
  description: "Esta aplicaci\xF3n contiene activos no libres"
NonFreeDep:
  description: "Esta aplicaci\xF3n depende de otras aplicaciones no gratuitas"
NonFreeNet:
  description: "Esta aplicaci\xF3n promueve servicios de red no gratuitos"
Tracking:
  description: "Esta aplicaci\xF3n realiza un seguimiento e informa de su actividad"
