App Store & Updater:
  name: Tienda de Aplicaciones y Actualizador
Bookmark:
  name: Marcador
Browser:
  name: Navegador
Calculator:
  name: Calculadora
Calendar & Agenda:
  name: Calendario y Agenda
Connectivity:
  name: Conectividad
Development:
  name: Desarrollo
Email:
  name: Email
Graphics:
  name: "Gr\xE1ficos"
Internet:
  name: Internet
Multimedia:
  name: Multimedia
Navigation:
  name: "Navegaci\xF3n"
Phone & SMS:
  name: "Tel\xE9fono & SMS"
Reading:
  name: Leyendo
Science & Education:
  name: "Ciencia y Educaci\xF3n"
Security:
  name: Seguridad
Sports & Health:
  name: Deportes & Salud
System:
  name: Sistema
Theming:
  name: "Personalizaci\xF3n"
VPN & Proxy:
  name: VPN & Proxy
Writing:
  name: Escribiendo
