Connectivity:
  name: "\u7DB2\u7D61"
Development:
  name: "\u958B\u767C"
Graphics:
  name: "\u5716\u50CF"
Internet:
  name: "\u4E92\u806F\u7DB2"
Multimedia:
  name: "\u591A\u5A92\u9AD4"
Navigation:
  name: "\u5C0E\u822A"
Phone & SMS:
  name: "\u96FB\u8A71\u540C\u77ED\u8A0A"
Reading:
  name: "\u958B\u5377"
Science & Education:
  name: "\u79D1\u5B78\u8207\u6559\u80B2"
Security:
  name: "\u4FDD\u5BC6"
Sports & Health:
  name: "\u904B\u52D5\u8207\u5065\u5EB7"
System:
  name: "\u7CFB\u7D71"
Theming:
  name: "\u4F48\u666F\u4E3B\u984C"
Writing:
  name: "\u5BEB\u4F5C"
