Ads:
  description: "Aquesta aplicaci\xF3 cont\xE9 publicitat"
  name: Anuncis
DisabledAlgorithm:
  description: "La signatura de seguretat de l'aplicaci\xF3 \xE9s feble"
  name: Signat amb un algoritme insegur
KnownVuln:
  description: "Aquesta aplicaci\xF3 t\xE9 un problema de seguretat conegut"
  name: Vulnerabilitat coneguda
NoSourceSince:
  description: "El codi font ja no \xE9s disponible, no \xE9s possible d'actualitzar"
  name: Sense font des de
NonFreeAdd:
  description: "Aquesta aplicaci\xF3 promou complements no lliures"
  name: Complements no lliures
NonFreeAssets:
  description: "Aquesta aplicaci\xF3 cont\xE9 recursos no lliures"
  name: "Recursos no gratu\xEFts"
NonFreeDep:
  description: "Aquesta aplicaci\xF3 dep\xE8n d'altres aplicacions no lliures"
  name: "Depend\xE8ncies no lliures"
NonFreeNet:
  description: "Aquesta aplicaci\xF3 promou o dep\xE8n completament de serveis de\
    \ xarxa no lliures"
  name: Serveis de xarxa no lliures
TetheredNet:
  description: "Aquesta aplicaci\xF3 dep\xE8n completament d'algunes inst\xE0ncies\
    \ d'un servei de xarxa"
  name: Serveis de Xarxes Vinculades (Tethered)
Tracking:
  description: "Aquesta aplicaci\xF3 segueix i informa sobre la vostra activitat"
  name: Seguiment
