AI Chat:
  description: "Assistents d'IA, robots de xat i interf\xEDcies de models de llenguatge\
    \ grans (LLM)"
  name: Xat d'IA
App Manager:
  description: "Gestiona, organitza i controla aplicacions instal\xB7lades, proposits\
    \ i permisos"
  name: Gestor d'aplicacions
App Store & Updater:
  description: "Descobreix, instal\xB7la i actualitza aplicacions des de repositoris\
    \ de programari"
  name: Botiga d'aplicacions i actualitzador
Battery:
  description: "Monitora i optimitza la vida de la bateria, l'\xFAs d'energia i la\
    \ c\xE0rrega"
  name: Bateria
Bookmark:
  description: "Guarda, organitza i gestiona els teus enlla\xE7os i llistes de lectura\
    \ preferides"
  name: "Adre\xE7a d'inter\xE8s"
Browser:
  description: "Navegadors web per navegar per internet i visualitzar les p\xE0gines\
    \ web"
  name: Navegador
Calculator:
  description: "Eines de c\xE0lcul aritm\xE8tic, cient\xEDfic i matem\xE0tic"
  name: Calculadora
Calendar & Agenda:
  description: Agenda d'esdeveniments, recordatoris, cites i planificadors diaris
  name: Calendaris i Agendes
Clock:
  name: Rellotge
Cloud Storage & File Sync:
  description: "Fes c\xF2pies de seguretat, sincronitza i accedeix a fitxers remotament\
    \ a trav\xE9s de serveis en el n\xFAvol"
  name: "Emmagatzematge al n\xFAvol i sincronitzaci\xF3 d'arxius"
Connectivity:
  name: Connectivitat
Contact:
  name: Contacte
DNS & Hosts:
  description: Configura DNS, bloqueig d'anuncis, fitxers hosts i enrutament de domini
  name: DNS i Allotjament
Development:
  description: "Eines de programaci\xF3, IDE, consola/terminal i desenvolupament"
  name: Desenvolupament
Draw:
  name: Dibuix
Ebook Reader:
  description: "Llegeix llibres electr\xF2nics, EPUB, PDF i llibres i publicacions\
    \ digitals"
  name: "Lector de llibres electr\xF2nics"
Email:
  description: "Clients de correu per enviar, rebre i gestionar missatges de correu\
    \ electr\xF2nic"
  name: "Correu electr\xF2nic"
File Encryption & Vault:
  description: Encripta, bloqueja i amaga fitxers i carpetes privades
  name: Xifratge de fitxers i caixa forta
File Transfer:
  name: "Transfer\xE8ncies de fitxers"
Finance Manager:
  description: Controla despeses, pressupostos, ingressos i comptes personals
  name: Gestor de finances
Firewall:
  description: "Bloqueja tr\xE0nsit de xarxa no desitjat i controla l'acc\xE9s a internet\
    \ de les aplicacions"
  name: Tallafoc
Flashlight:
  name: Llanterna
Forum:
  name: "F\xF2rum"
Gallery:
  description: "Navega, visualitza i organitza fotos, imatges i v\xEDdeos"
  name: Galeria
Graphics:
  name: "Gr\xE0fics"
Habit Tracker:
  name: "Registre d'h\xE0bits"
Icon Pack:
  name: Pack d'icones
Internet:
  name: Internet
Inventory:
  name: Inventari
Keyboard & IME:
  name: Teclat i IME
Launcher:
  name: "Llan\xE7ador"
Local Media Player:
  name: Reproductor local de mitjans
Location Tracker & Sharer:
  name: "Seguiment i compartici\xF3 d'ubicaci\xF3"
Messaging:
  name: Missatges
Multimedia:
  name: "Multim\xE8dia"
Music Practice Tool:
  name: "Eina de pr\xE0ctica musical"
Navigation:
  name: "Navegaci\xF3"
Network Analyzer:
  name: Analitzador de xarxa
News:
  name: "Not\xEDcies"
Note:
  name: Notes
Online Media Player:
  name: "Reproductor de mitjans en l\xEDnia"
Pass Wallet:
  name: Cartera de paraules de pas
Password & 2FA:
  name: "Paraules de pas i autenticaci\xF3 de dos factors"
Phone & SMS:
  name: "M\xF2bil i missatgeria"
Podcast:
  name: Podcast
Public Transport:
  name: "Mapa de transport p\xFAblic i horaris"
Reading:
  name: Lectura
Recipe Manager:
  name: Gestor de receptes
Religion:
  name: "Religi\xF3"
Science & Education:
  name: "Ci\xE8ncia i educaci\xF3"
Security:
  name: Seguretat
Shopping List:
  name: Llista de la compra
Social Network:
  name: Xarxes socials
Sports & Health:
  name: Esports i Salut
System:
  name: Sistema
Task:
  name: Tasques
Text Editor:
  name: Editor de text
Theming:
  name: Temes
Translation & Dictionary:
  name: "Traducci\xF3 i diccionari"
Unit Convertor:
  name: Convertidor d'unitats
VPN & Proxy:
  name: VPN i Proxy
Voice & Video Chat:
  name: "Xat de veu i v\xEDdeo"
Wallet:
  name: Cartera
Wallpaper:
  name: Fons de pantalla
Weather:
  name: Clima
Workout:
  name: Entrenament
Writing:
  name: Escriptura
