archive:
  description: "L'arxiu del repositori oficial de programari lliure F-Droid. Les aplicacions\
    \ aqu\xED s\xF3n antigues i poden contenir vulnerabilitats i problemes de seguretat\
    \ coneguts!"
  name: Arxiu F-Droid
repo:
  description: El repositori oficial de programari lliure F-Droid. Tot en aquest repositori
    sempre es construeix a partir del codi font.
  name: F-Droid
