Connectivity:
  name: "Gir\xEAdan\xEE"
Development:
  name: "P\xEA\u015Fdebirin"
Graphics:
  name: "Graf\xEEk"
Internet:
  name: "\xCEnternet"
Phone & SMS:
  name: Telefon & SMS
Reading:
  name: Xwendin
Science & Education:
  name: Zanist & perwerde
Security:
  name: "Ewleh\xEE"
Sports & Health:
  name: "Werzi\u015F\xEE & tendurist\xEE"
System:
  name: Pergal
Writing:
  name: "Niv\xEEsandin"
