Ads:
  description: "\u0160ioje program\u0117l\u0117je yra reklam\u0173"
  name: Skelbimai
DisabledAlgorithm:
  description: "\u0160i program\u0117l\u0117 turi silpn\u0105 saugumo para\u0161\u0105"
  name: "Pasira\u0161yta naudojant nesaug\u0173 algoritm\u0105"
KnownVuln:
  description: "\u0160ioje program\u0117l\u0117je yra \u017Einomas saugumo pa\u017E\
    eid\u017Eiamumas"
  name: "\u017Dinomas pa\u017Eeid\u017Eiamumas"
NoSourceSince:
  description: "\u0160altinio kodas nebeprieinamas, atnaujinimai negalimi"
  name: "Neb\u0117ra \u0161altinio"
NonFreeAdd:
  description: "\u0160i program\u0117l\u0117 propaguoja ne laisvosios programin\u0117\
    s \u012Frangos papildinius"
  name: Ne atviro kodo papildiniai
NonFreeAssets:
  description: "\u0160ioje program\u0117l\u0117je yra mokam\u0173 resurs\u0173"
  name: Mokami resursai
NonFreeDep:
  description: "\u0160i program\u0117l\u0117 priklauso nuo kit\u0173 u\u017Edaro kodo\
    \ program\u0117li\u0173"
  name: "Nuo u\u017Edaro kodo priklausomos program\u0117l\u0117s"
NonFreeNet:
  description: "\u0160i program\u0117l\u0117 propaguoja priva\u010Di\u0105 tinklo\
    \ paslaug\u0105 arba nuo jos priklauso"
  name: Ne atviro kodo tinklo paslaugos
TetheredNet:
  description: "\u0160i program\u0117l\u0117 visi\u0161kai priklauso nuo tam tikro\
    \ tinklo paslaugos atvejo"
  name: "Priri\u0161to tinklo paslaugos"
Tracking:
  description: "\u0160i program\u0117l\u0117 seka ir perduoda j\u016Bs\u0173 veikl\u0105"
  name: Sekimas
