AI Chat:
  description: "DI asistentai, pokalbi\u0173 botai ir didel\u0117s kalbos modeli\u0173\
    \ (LLM) s\u0105sajos"
  name: DI pokalbis
Action Game:
  description: "Veiksmo, sporto, lenktyni\u0173 ir platform\u0173 \u017Eaidimai"
  name: "Veiksmo \u017Eaidimas"
Alarm Clock:
  description: "Nustatykite \u017Eadintuv\u0105"
  name: "\u017Dadintuvas"
App Manager:
  name: "Program\u0173 tvarkykl\u0117"
App Store & Updater:
  description: "Atraskite, \u012Fdiekite ir atnaujinkite program\u0117les i\u0161\
    \ prog. \u012Frangos saugykl\u0173"
  name: "Program\u0117li\u0173 parduotuv\u0117 ir atnaujintuvas"
Battery:
  description: "Steb\u0117kite ir optimizuokite baterijos veikimo trukm\u0119, energijos\
    \ naudojim\u0105 ir \u012Fkrovim\u0105"
  name: Baterija
Board Game:
  description: "Stalo \u017Eaidimas, \u0161achmatai, go, kry\u017Eiukai-nuliukai"
  name: "Stalo \u017Eaidimas"
Bookmark:
  description: "I\u0161saugokite ir tvarkykite m\u0117gstamiausias nuorodas ir skaitymo\
    \ s\u0105ra\u0161us"
  name: "\u017Dym\u0117"
Browser:
  description: "\u017Diniatinklio nar\u0161ykl\u0117s paie\u0161kai internete ir svetaini\u0173\
    \ per\u017Ei\u016Brai"
  name: "Nar\u0161ykl\u0117"
Calculator:
  description: "Aritmetiniai, moksliniai ir matematiniai skai\u010Diavimo \u012Frankiai"
  name: "Skai\u010Diuotuvas"
Calendar & Agenda:
  description: "Planuokite \u012Fvykius, priminimus, konsultacijas ir dienos planus"
  name: "Kalendorius ir darbotvark\u0117"
Camera:
  description: "Fotoaparatas, IP vaizdo kameros ir vaizdo \u012Fra\u0161ymas"
  name: Fotoaparatas
Card Game:
  description: "Kort\u0173 \u017Eaidimas, pasjansas"
  name: "Kort\u0173 \u017Eaidimas"
Cloud Storage & File Sync:
  name: "Saugykla debesyje ir fail\u0173 sinchronizavimas"
Connectivity:
  name: "Ry\u0161iai ir tinklas"
DNS & Hosts:
  name: DNS ir serveriai
Development:
  name: "Pl\u0117tojimas"
Draw:
  name: "Pie\u0161imas"
Ebook Reader:
  name: "El. knyg\u0173 skaitykl\u0117"
Email:
  name: "Elektroninis pa\u0161tas"
File Encryption & Vault:
  name: "Fail\u0173 \u0161ifravimas ir saugykla"
File Transfer:
  name: "Fail\u0173 perk\u0117limas"
Finance Manager:
  name: "Finans\u0173 valdykl\u0117"
Forum:
  name: Forumas
Gallery:
  name: Galerija
Graphics:
  name: Grafika
Habit Tracker:
  name: "\u012Epro\u010Di\u0173 sekiklis"
Icon Pack:
  name: "Piktogram\u0173 pakas"
Internet:
  name: Internetas
Keyboard & IME:
  name: "Klaviat\u016Bra ir \u012Fvesties metodai (IME)"
Launcher:
  name: Paleidimo programa
Local Media Player:
  name: "Vietin\u0117s medijos leistuv\u0117"
Location Tracker & Sharer:
  name: "Vietov\u0117s sekimo ir bendrinimo \u012Frankis"
Messaging:
  name: "Susira\u0161in\u0117jimas"
Multimedia:
  name: Multimedija
Music Practice Tool:
  name: "Muzikin\u0117s praktikos \u012Frankis"
Navigation:
  name: Navigacija
News:
  name: Naujienos
Note:
  name: Pastaba
Online Media Player:
  name: "Internetin\u0117 medijos leistuv\u0117"
Pass Wallet:
  name: "Biliet\u0173 pinigin\u0117"
Password & 2FA:
  name: "Slapta\u017Eod\u017Eiai ir 2 fakt. autentif."
Phone & SMS:
  name: Telefonas ir SMS
Podcast:
  name: "Tinklalaid\u0117"
Public Transport:
  name: "Vie\u0161. transp. \u017Eem\u0117lapis ir tvarkara\u0161tis"
Reading:
  name: Skaitymas
Recipe Manager:
  name: "Recept\u0173 tvarkykl\u0117"
Science & Education:
  name: "Mokslas ir \u0161vietimas"
Security:
  name: Saugumas
Shopping List:
  name: "Pirkini\u0173 s\u0105ra\u0161as"
Social Network:
  name: Socialinis tinklas
Sports & Health:
  name: Sportas ir sveikata
System:
  name: Sistema
Task:
  name: "U\u017Eduotis"
Text Editor:
  name: "Tekst\u0173 redaktorius"
Theming:
  name: Apipavidalinimas
Translation & Dictionary:
  name: "Vertimas ir \u017Eodynas"
Unit Convertor:
  name: "Vienet\u0173 keitiklis"
VPN & Proxy:
  name: "VPN ir \u012Fgaliotieji serveriai"
Voice & Video Chat:
  name: Balso ir garso pokalbiai
Wallet:
  name: "Pinigin\u0117"
Wallpaper:
  name: "U\u017Esklanda"
Weather:
  name: Orai
Workout:
  name: "Treniruot\u0117"
Writing:
  name: "Ra\u0161ymas"
