Ads:
  description: Selles rakenduses on reklaame
  name: Reklaamid
DisabledAlgorithm:
  description: "Sellel rakendusel on n\xF5rk turvallkiri"
  name: Allkirjastamisel on kasutatud ebaturvalist algoritmi
KnownVuln:
  description: "Sellel rakendusel on tuntud turvan\xF5rkus"
  name: "Tuntud turvan\xF5rkus"
NoSourceSince:
  description: "L\xE4htekood ei ole enam saadaval, uuendused ei ole enam v\xF5imalikud"
  name: "L\xE4htekood pole saadaval alates"
NonFreeAdd:
  description: See rakendus edendab mitte-vabu laiendusi
  name: Mitte-vabad laiendused
NonFreeAssets:
  description: Selles rakenduses on mitte-vabu komponente
  name: Mitte-vabad vara
NonFreeDep:
  description: "See rakendus s\xF5ltub teistest mitte-vabadest rakendustest"
  name: "Mitte-vabad S\xF5ltuvused"
NonFreeNet:
  description: "See rakendus eelistab mitte-vabu v\xF5rguteenuseid v\xF5i s\xF5ltub\
    \ nendest"
  name: "Mitte-vabad v\xF5rguteenuseid"
TetheredNet:
  description: "See rakendus s\xF5ltub t\xE4ielikult \xFChest kindlast v\xF5rguteenusest"
  name: "L\xF5astatud v\xF5rguteenused"
Tracking:
  description: "See rakendus j\xE4lgib ja raporteerib su aktiivsusest"
  name: "J\xE4lgimine"
