AI Chat:
  description: Tehisaru abilised, vestlusrobotid ja suurte keelemudelite (LLM) liidesed
  name: Vestlus tehisaruga
Action Game:
  description: "M\xE4rul, sport, v\xF5idus\xF5idud ja platvormim\xE4ngud"
  name: "M\xE4rulim\xE4ngud"
Alarm Clock:
  description: "\xC4ratuse seadistamine"
  name: "\xC4ratuskell"
App Manager:
  description: "Halda ja korralda paigaldatud rakendusi, seoseid ja \xF5igusi"
  name: Rakendustehaldur
App Store & Updater:
  description: Otsi, paigalda ja uuenda rakendusi tarkvarahoidlatest
  name: Rakendustepoed ja uuendused
Battery:
  description: "J\xE4lgi ja optimeeri aku eluiga, toitekasutust ja laadimist"
  name: Akuhaldus
Board Game:
  description: "Lauam\xE4ng, male, go, trips-traps-trull"
  name: "Lauam\xE4ngud"
Bookmark:
  description: Salvesta, halda ja korralda lemmiklinke ja lugemisloendeid
  name: "J\xE4rjehoidjad"
Browser:
  description: Veebibrauserid internetis surfamiseks ja veebilehtede vaatamiseks
  name: Veebibrauserid
Calculator:
  description: Aritmeetilised, teaduslikud ja matemaatilised arvutustarvikud
  name: Kalkulaatorid
Calendar & Agenda:
  description: "Kavanda s\xFCndmusi, meeldetuletusi, kohtumisi ja p\xE4evakavasid"
  name: "Kalender ja p\xE4evakava"
Camera:
  description: Kaamerad, IP-kaamerate kliendid ja videosalvestus
  name: Kaamera
Card Game:
  description: "Kaardim\xE4ng, pasjanss"
  name: "Kaardim\xE4ngud"
Cast:
  description: Meedialevitus, UPnP, DLNA, FCast, AirPlay, Miracast
  name: Meedialevi
Casual Game:
  description: "Lihtne m\xE4ng vabaks ajaks"
  name: "Vabaaja m\xE4ngud"
Clock:
  description: Teave hetke kellaaja kohta
  name: Kellad
Cloud Storage & File Sync:
  description: "Varundus, s\xFCnkroonimine ja failide kaugjuurdep\xE4\xE4s pilveteenuste\
    \ kaudu"
  name: "Pilveruum ja s\xFCnkroonimine"
Code & Forge:
  description: "Git, forge, l\xE4htekoodi haldus ja majutus"
  name: Koodi kirjutamine ja haldus
Connectivity:
  name: "\xDChenduvus"
Contact:
  description: Aadressiraamatud, telefoniraamatud ja kontaktide haldamise rakendused
  name: Kontaktihaldus
DNS & Hosts:
  description: Seadista nimelahendust, reklaamide blokeerimist hosts-faili ja domeenide
    suunamist
  name: Nimelahendus ja hostid
Development:
  description: Koodimine, programmeerimine, IDE, terminal ja arendajate tarvikud
  name: Arendus
Dice:
  description: "Juhuslikul valiku p\xF5hinevad m\xE4ngud"
  name: "T\xE4ringum\xE4ngud"
Diet:
  description: "Toitumine, kalorid, toidu tarbimise haldamine ja j\xE4lgimine"
  name: Toiduvalik
Download:
  description: Allalaadimine, allalaadimishaldurid, torrentikliendid
  name: Allalaadimised
Draw:
  description: Joonistamine, maalimine, illustratsioonid ja digitaalkunsti rakendused
  name: Joonistamine
Ebook Reader:
  description: "Loe e-raamatuid, EPUB-faile, PDF-faile ning digitaalseid raamatuid\
    \ ja v\xE4ljaandeid"
  name: E-raamatute lugemine
Educational Game:
  description: "\xD5ppimine m\xE4ngu ajal, k\xFCsimustikud, viktoriinid"
  name: "Harivad m\xE4ngud"
Email:
  description: "E-posti kliendid e-kirjade saatmiseks, vastuv\xF5tmiseks ja haldamiseks"
  name: E-post
Emulator:
  description: "M\xE4ngude ja programmide k\xE4ivitamise emulaatorid"
  name: Emulaatorid
File Encryption & Vault:
  description: "Kr\xFCpti, lukusta ja peida isiklikud failid ja kaustad"
  name: "Kr\xFCptimine ja andmehoidlad"
File Manager:
  description: Failide haldus ja uurimine
  name: Failihaldurid
File Transfer:
  description: "Jaga ja edasta faile FTP, kohtv\xF5rgu, Bluetoothi v\xF5i v\xF5rd\xF5\
    igusv\xF5rgu (p2p) kaudu"
  name: Failide edastamine
Finance Manager:
  description: "J\xE4lgi kulusid, eelarveid, sissetulekuid ja oma pangakontosid"
  name: Rahahaldus
Firewall:
  description: "Blokeeri soovimatut v\xF5rguliiklust ja piira rakenduste interneti\xFC\
    hendust"
  name: "Tulem\xFC\xFCrid"
Flashlight:
  description: "Taskulambid ja LED-v\xE4lklampide rakendused"
  name: "V\xE4lklambid"
Forum:
  description: "Arutelufoorumid, kogukonna jutul\xF5ngad ja k\xFCsimuste-vastuste\
    \ platvormid"
  name: Foorumid
Gallery:
  description: Sirvi, vaata ja korralda fotosid, pilte ja videoid
  name: Galeriid
Game Helper:
  description: "M\xE4ngutarvikud, abilised, kaaslased, tulemused, edetabelid, taimerid"
  name: "M\xE4ngude abitarvikud"
Graphics:
  description: "Pildit\xF6\xF6tlus-, fotot\xF6\xF6tlus- ja visuaalse disaini tarvikud"
  name: Graafika
Habit Tracker:
  description: "Koosta elurutiine, j\xE4lgi igap\xE4evaseid eesm\xE4rke ja hoia silma\
    \ peal oma j\xE4rjestikustel saavutustel"
  name: Elustiil
Health Manager:
  description: "J\xE4lgi kehakaalu, pulssi, verer\xF5hku, menstruatsiooni ja muid\
    \ tervisen\xE4itajaid"
  name: Tervisehaldus
Icon Pack:
  description: Kohandatud ikoonikomplektid rakenduste ikoonide kujundamiseks
  name: Ikoonipakid
Internet:
  name: Internet
Inventory:
  description: "F\xFC\xFCsiliste esemete ja varude j\xE4lgimine, kataloogimine ja\
    \ haldamine"
  name: Varahaldus
Keyboard & IME:
  description: Kohandatud klahvistikud, sisestusmeetodid, automaatkorrektuur ja kirjutamisrakendused
  name: Klahvistik ja sisendmeetodid
Launcher:
  description: "Erinevad nutiseadme avalehe variandid ja t\xF6\xF6lauakeskkonna rakendused"
  name: "K\xE4ivitajad"
Local Media Player:
  description: "Esita seadmes salvestatud heli- ja videofaile v\xF5rgu\xFChendust\
    \ kasutamata"
  name: Meediaesitus nutiseadmest
Location Tracker & Sharer:
  description: "Jaga ja j\xE4lgi reaalajas GPS-asukohta teistega"
  name: Asukoha logimine ja jagamine
Lyrics:
  description: "Vaata ja otsi laulus\xF5nu"
  name: "Laulus\xF5nad"
Market & Price:
  description: "Hinnad, valuutakursid, b\xF6rsinoteeringud"
  name: Turud ja hinnad
Meditation:
  description: Meditatsioon, teadvelolek, hingamisharjutused
  name: Mediteerimine
Messaging:
  description: Kiirsuhtlus-, vestlus- ja SMS-rakendused
  name: "S\xF5numirakendused"
Multimedia:
  name: Multimeedia
Music Practice Tool:
  description: "H\xE4\xE4lestusseadmed, metronoomid, akordit\xF6\xF6riistad ja pilliharjutamise\
    \ abivahendid"
  name: Muusikatarvikud
Navigation:
  description: Kaardid, GPS, samm-sammult juhised ja teejuhatamise rakendused
  name: Tee juhatamine
Network Analyzer:
  description: "WiFi-v\xF5rkude diagnostika ja skannimine ning \xFChenduse toimivuse\
    \ j\xE4lgimine"
  name: "V\xF5rguanal\xFC\xFCs"
News:
  description: Viimased uudised, artiklid, RSS-uudisvood ja uudiste koondajad
  name: Uudised
Note:
  description: "M\xE4rkmikud, meeldetuletused ning kiire m\xE4rkmete tegemise ja haldamise\
    \ rakendused"
  name: "M\xE4rkmikud"
Notification:
  description: Teavituste haldus, logimine, edasisuunamine
  name: Teavitused
OCR:
  description: "Dokumendiskanner, optiline m\xE4rgituvastus ja t\xE4hetuvastus"
  name: "Optiline m\xE4rgituvastus"
Online Media Player:
  description: "Kuula muusikat, vaata videoid ja j\xE4lgi otse\xFClekandeid internetist"
  name: "Meediaesitus v\xF5rgust"
Party Game:
  description: "M\xE4ngupeod, m\xE4ngud mitmele, v\xF5rgum\xE4ngud"
  name: "Peom\xE4ngud"
Pass Wallet:
  description: Salvesta ja halda pardakaarte, pileteid, kliendikaarte ja kuponge
  name: Raha- ja kaarditaskud
Password & 2FA:
  description: "Salas\xF5nahaldurid, autentimisseadmed, OTP, TOTP, HOTP, U2F, FIDO\
    \ ja kahefaktorilise autentimise tarvikud"
  name: "Salas\xF5nad ja 2FA"
Phone & SMS:
  description: "K\xF5nevalijad, k\xF5nehaldurid ja tekstis\xF5numite saatmise rakendused"
  name: Telefon ja SMS
Platformer Game:
  description: "M\xE4ngud tasanditel ja k\xFClgvaates"
  name: "Platvormim\xE4ngud"
Podcast:
  description: "Telli, kuula ja laadi alla taskuh\xE4\xE4linguid ning saateid"
  name: "Taskuh\xE4\xE4ling"
Public Transport:
  description: "Bussi-, rongi-, metroo- ja muu \xFChistranspordi s\xF5iduplaanid ning\
    \ teekonna kavandajad"
  name: "\xDChistransport ja s\xF5iduplaanid"
Push:
  description: "T\xF5ukes\xF5numid"
  name: "T\xF5uketeenused"
Puzzle Game:
  description: "M\xF5istatused,pusled, sudoku, m\xE4luharjutused"
  name: "M\xF5istatusm\xE4ngud"
Radio:
  description: "Kuula otse\xFClekandes FM/AM-raadiojaamu ja internetiraadiojaamu"
  name: Raadio
Reading:
  description: Artiklid, pikemad tekstid, hilisemaks lugemiseks salvestamise rakendused
    ja veebilugemisrakendused
  name: Lugemine
Recipe Manager:
  description: "Salvesta, korralda ja avasta toiduvalmistamisretsepte ning s\xF6\xF6\
    gitegemise ideid"
  name: Retseptihaldus
Recorder:
  description: "Heli-, ekraani- ja k\xF5nesalvestus"
  name: Salvestaja
Religion:
  description: "Palveajad, p\xFChad tekstid, vaimulikud lugemised ja vaimse praktika\
    \ rakendused"
  name: Usk ja religioon
Remote Access:
  description: "Halda arvuteid, servereid ja seadmeid kaugjuhtimise teel RDP, VNC\
    \ v\xF5i SSH abil"
  name: "Kaugligip\xE4\xE4s"
Remote Controller:
  description: Infrapuna- ja nutikodu puldid teleritele, kliima- ja muudele seadmetele
  name: Kaugjuhtimispuldid
Role-Playing Game:
  description: "Rollim\xE4ngud (RPG) ja (vangi)koobastiku m\xE4ngud, D&D-t\xFC\xFC\
    pi m\xE4ngud"
  name: "Rollim\xE4ngud"
Schedule:
  description: "Konverentside ja \xFCrituste p\xE4evaplaanid ja -kavad"
  name: "\xDCrituste p\xE4evakavad"
Science & Education:
  description: "\xD5ppimis-, uurimis-, teabe- ja haridusrakendused"
  name: Teadus ja haridus
Security:
  name: Turvalisus
Shooter Game:
  description: "Sihtm\xE4rgi tabamisega seotud m\xE4ngud"
  name: "Laskmism\xE4ngud"
Shopping List:
  description: "Ostunimekirjad, ostude j\xE4lgimise rakendused ja \xFChisostmise rakendused"
  name: Ostunimekirjad
Social Network:
  description: Sotsiaalmeedia, mikroblogimine ja veebikogukondade platvormid
  name: "Sotsiaalv\xF5rgustik"
Sport Game:
  description: Digitaalne sport, e-sport
  name: "Spordim\xE4ngud"
Sports & Health:
  description: "Treeningute j\xE4lgimine, heaolu, sporditulemused ja tervise j\xE4\
    lgimine"
  name: Sport ja tervis
Stopwatch:
  description: "Edenemise, m\xF6\xF6dunud aja v\xF5i ringi aja m\xF5\xF5tmine"
  name: Stopper
Strategy Game:
  description: Strateegiad ja simulatsioonid
  name: "Strateegiam\xE4ngud"
System:
  name: "S\xFCsteem"
Task:
  description: "\xDClesannete haldurid ning tootlikkuse ja GTD-tarvikud"
  name: "\xDClesanded"
Text Editor:
  description: Vormindamata teksti redaktorid, Markdowni redaktorid ja kirjutamisvahendid
  name: Tekstitoimetid
Text to Speech:
  description: "K\xF5nes\xFCnteesi (tekst k\xF5neks) tarvikud"
  name: "K\xF5nes\xFCntees"
Theming:
  description: "Kohanda oma nutiseadme v\xE4limust kujunduste, kirjat\xFC\xFCpide\
    \ ja kasutajaliidese stiilide abil"
  name: Kujundused
Time Tracker:
  description: "J\xE4lgi tegevustele kulunud aega ja ekraaniaega"
  name: "Ajakasutuse j\xE4lgimine"
Timer:
  description: "Taimer, ajaarvestus, p\xF6\xF6rdloendus, ajast kinni pidamine"
  name: Taimerid
Translation & Dictionary:
  description: "T\xF5lgi keete vaheli, otsi s\xF5nade t\xE4hendusi ja kasuta s\xF5\
    nastikke"
  name: "T\xF5lkimine ja s\xF5nastikud"
Unit Convertor:
  description: "Teisenda pikkuse, kaalu, temperatuuri, valuuta ja muid \xFChikuid"
  name: "\xDChikute teisendajad"
VPN & Proxy:
  description: "Kr\xFCpti andmesidet, v\xE4ldi piirangud ja muuda oma v\xF5rgu\xFC\
    hendus anon\xFC\xFCmseks"
  name: VPN-id ja proksiteenused
Visual Novel:
  description: "Visuaalromaan, jutum\xE4ngud, jaapani gal-m\xE4ngud"
  name: Visuaalromaanid
Voice & Video Chat:
  description: "H\xE4\xE4l- ja videok\xF5ned, konverentsk\xF5ned ning VoIP-suhtlusrakendused"
  name: "H\xE4\xE4l- ja videovestlused"
Volume:
  description: Helivaljuse seadistuste haldus
  name: Helivaljus
Wallet:
  description: "Digitaalsed rahakotid maksete tegemiseks, kaartide ja kr\xFCptovaluutade\
    \ haldamiseks"
  name: Dokumendi- ja rahataskud
Wallpaper:
  description: Avalehe ja lukustusvaate taustapildid ning reaalajas muutuvad taustapildid
  name: Taustapildid
Weather:
  description: "Ilmaennustused, radari\xFClevaated, temperatuur ja ilmastikutingimused"
  name: Ilmaennustus
Word Game:
  description: "S\xF5napusled, rists\xF5nad, s\xF5nade \xE4raarvamised"
  name: "S\xF5nam\xE4ngud"
Workout:
  description: "Treeningute kavad, j\xF5usaali treeningute j\xE4lgimine, jooksmine\
    \ ja fitnessi treeningurakendused"
  name: Treening
Writing:
  description: "Tekstit\xF6\xF6tlusprogrammid, p\xE4evikute pidamise, kavandite koostamise\
    \ ja pikemate tekstide kirjutamise rakendused"
  name: Kirjutamine
