Ads:
  description: "Esta aplicaci\xF3n tiene publicidad"
  name: Anuncios
DisabledAlgorithm:
  description: "Esta aplicaci\xF3n tiene una firma de seguridad d\xE9bil"
  name: Firmado mediante un algoritmo inseguro
KnownVuln:
  description: "Esta aplicaci\xF3n contiene una vulnerabilidad de seguridad conocida"
  name: Vulnerabilidad conocida
NoSourceSince:
  description: "El c\xF3digo fuente ya no est\xE1 disponible, no se puede realizar\
    \ actualizaciones"
  name: Sin fuente desde
NonFreeAdd:
  description: "Esta aplicaci\xF3n promueve complementos no libres"
  name: Complementos de pago
NonFreeAssets:
  description: "Esta aplicaci\xF3n contiene recursos no libres"
  name: Activos no gratuitos
NonFreeDep:
  description: "Esta aplicaci\xF3n depende de otras aplicaciones no libres"
  name: Dependencias no gratuitas
NonFreeNet:
  description: "Esta aplicaci\xF3n promueve servicios no libres"
  name: Servicios de red no gratuitos
TetheredNet:
  description: "Esta aplicaci\xF3n depende completamente de una instancia espec\xED\
    fica de un servicio de red"
  name: Servicios de red conectados
Tracking:
  description: "Esta aplicaci\xF3n rastrea e informa de tu actividad"
  name: Seguimiento
