Ads:
  description: Asnas-a yegber adellel
DisabledAlgorithm:
  description: "Asnas-a yes\u025Ba azmul i ixu\u1E63\u1E63en deg t\u0263ellist"
NoSourceSince:
  name: "Tangalt ta\u0263balut dayen ur telli ara, ulac ileqman."
NonFreeAdd:
  description: Asnas-a yegber Izegrar ur nelli ara d ilelliyen
NonFreeAssets:
  description: "Asnas-a yegber i\u1E25ricen ur nelli ara d ilelliyen"
NonFreeDep:
  description: "Asnas-a icudd \u0263er yisnasen-nni\u1E0Den ur nelli ara d ilelliyen"
NonFreeNet:
  description: "Asnas-a isnernay ime\u1E93liyen n u\u1E93e\u1E6D\u1E6Da ur nelli ara\
    \ d ilelliyen"
Tracking:
  description: "Asnas-a ad ye\u1E0Dfe\u1E5B udi\u0263 ad d-yazen armud-ik"
