Browser:
  name: Merdeer
Clock:
  name: Horolaj
Connectivity:
  name: Kevreadusted
Development:
  name: Diorren
Email:
  name: Postel
Forum:
  name: Forom
Graphics:
  name: Graferezh
Internet:
  name: Internet
Multimedia:
  name: Liesvedia
Navigation:
  name: "Merdei\xF1"
News:
  name: Keleier
Phone & SMS:
  name: Pellgomz hag SMS
Podcast:
  name: Podskign
Reading:
  name: Lenn
Science & Education:
  name: "Skianto\xF9 ha deskadurezh"
Security:
  name: Diogelroez
Sports & Health:
  name: "Sporto\xF9 ha yec'hed"
System:
  name: Reizhiad
Theming:
  name: Neuz
Weather:
  name: Amzer
Writing:
  name: "Skriva\xF1"
