Ads:
  description: "Diese App enth\xE4lt Werbung"
  name: Werbung
DisabledAlgorithm:
  description: Diese App hat eine schwache Sicherheitssignatur
  name: Mit einem unsicheren Algorithmus signiert
KnownVuln:
  description: "Diese App enth\xE4lt eine bekannte Sicherheitsl\xFCcke"
  name: "Bekannte Sicherheitsl\xFCcke"
NoSourceSince:
  description: "Der Quellcode ist nicht mehr verf\xFCgbar, keine Aktualisierungen\
    \ m\xF6glich"
  name: Keine Quelle seit
NonFreeAdd:
  description: Diese App bewirbt nicht-quelloffene Erweiterungen
  name: Nicht-quelloffene Erweiterungen
NonFreeAssets:
  description: "Diese App enth\xE4lt nicht-quelloffene Bestandteile"
  name: Nicht-quelloffene Bestandteile
NonFreeDep:
  description: "Diese App ist abh\xE4ngig von anderen nicht-quelloffenen Apps"
  name: "Nicht-quelloffene Abh\xE4ngigkeiten"
NonFreeNet:
  description: "Diese App bewirbt oder h\xE4ngt vollst\xE4ndig von einem nicht-quelloffenen\
    \ Netzwerkdienst ab"
  name: Nicht-quelloffene Netzwerkdienste
TetheredNet:
  description: "Diese App h\xE4ngt vollst\xE4ndig von einer bestimmten Instanz eines\
    \ Netzwerkdienstes ab"
  name: Verbundene Netzwerkdienste
Tracking:
  description: "Diese App verfolgt und versendet deine Aktivit\xE4ten"
  name: Tracking
