archive:
  description: "Das Archiv des offiziellen F-Droid-Repository f\xFCr Freie Software.\
    \ Diese Apps hier sind alt und k\xF6nnen bekannte Schwachstellen und Sicherheitsprobleme\
    \ enthalten!"
  name: F-Droid-Archiv
repo:
  description: "Das offizielle F-Droid-Repository f\xFCr Freie Software. Alles in\
    \ diesem Repository wird immer aus dem Quellcode erstellt."
  name: F-Droid
