Connectivity:
  name: "Conectivid\xE1"
Development:
  name: Desendolcu
Graphics:
  name: Graphics
Internet:
  name: Internet
Multimedia:
  name: Multimedia
Navigation:
  name: "Navegaci\xF3n"
Phone & SMS:
  name: "Telefon\xEDa y SMS"
Reading:
  name: Llectura
Science & Education:
  name: "Ciencia y educaci\xF3n"
Security:
  name: Seguranza
Sports & Health:
  name: "Deporte y sal\xFA"
System:
  name: Sistema
Theming:
  name: Aspeutu
Writing:
  name: Escritura
