archive:
  description: "Archiv ofici\xE1ln\xEDho repozit\xE1\u0159e svobodn\xE9ho softwaru\
    \ F-Droid. Aplikace zde jsou zastaral\xE9 a mohou obsahovat zn\xE1m\xE9 zranitelnosti\
    \ a bezpe\u010Dnostn\xED probl\xE9my!"
  name: Archiv F-Droid
repo:
  description: "Ofici\xE1ln\xED repozit\xE1\u0159 svobodn\xE9ho softwaru F-Droid.\
    \ V\u0161e v tomto repozit\xE1\u0159i je v\u017Edy sestaveno ze zdrojov\xE9ho\
    \ k\xF3du."
  name: F-Droid
