name: Android Release Build

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build & Release APK
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.4'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build FOSS APK
        # Le "|| true" empêche GitHub de tout couper si Flutter fait son erreur de fichier introuvable
        run: flutter build apk --flavor foss --release || true

      - name: Upload FOSS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-foss-apk
          # Les étoiles permettent de fouiller dans tous les sous-dossiers pour trouver l'APK
          path: build/app/outputs/**/*.apk

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          # Idem ici, le joker ramasse l'APK pour le mettre dans la release
          files: build/app/outputs/**/*.apk
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
